bcgov/business-create-ui

src/components/DefineCompany/BusinessContactInfo.vue
tests/unit/BusinessContactInfo.spec.ts

*Issue #:* /bcgov/entity#2344
Added unit tests for Business Contact Info
Added id to the ui elements

Business Contact Info unit test + Adding id to the ui elements

---

package-lock.json
public/config/configuration.json
src/App.vue
src/components/DefineCompany/OfficeAddresses.vue
src/constants/constants.ts
src/interfaces/filing-interfaces/filing-interface.ts
src/interfaces/stepper-interfaces/DefineCompany/define-company-interface.ts
src/mixins/filing-template-mixin.ts
src/mixins/legal-api-mixin.ts
src/store/actions/actions-model.ts
src/store/getters/state-getters.ts
src/store/index.ts
src/store/mutations/mutations-model.ts
src/store/state/state-model.ts
src/views/DefineCompany.vue
tests/unit/Actions.spec.ts
tests/unit/App.spec.ts
tests/unit/DefineCompany.spec.ts
tests/unit/OfficeAddresses.spec.ts

*Issue #:* /bcgov/entity#2582
* Updates the saving / filing incorporations filings.
* Implements a means to fetch and parse draft filings into the ui.
* Updates unit testing.
* Notes: Currently there is no dashboard to launch a draft from. This is mocked by setting a nrNumber in the App.vue ( line 100 ). If you save a filing to the specified number you will retrieve and parse the draft based off what nrNumber is set. 
* Future state: We will inject an nrNumber or other equivalent identifier into the front end from wherever we launch incorporation filings from.

#2582 Handling Saving and Fetching Draft Filings

---

tests/unit/Actions.spec.ts

Signed-off-by: Kial Jinnah <kialj876@gmail.com>
*Issue #:* /bcgov/entity#2777
- the axios call in the 'createFiling' method wasn't stubbed so it was causing the econfused error
- since these tests weren't testing the createFiling method (it was just getting called as a side effect of what was being tested) I decided to mock the createFiling method to do nothing.

fixed jest console errors

---

src/common/FeatureFlags.ts

…n the config map
*Issue #:* /bcgov/entity#2855
Noticed that if the ld client id is empty in the config map, the value is getting set as undefined. Specifying a fall back key will solve the issue. The fall back key can be any value

Adding the fall back key for ld client id

---

package-lock.json
package.json
src/App.vue
src/mixins/legal-api-mixin.ts
src/router/index.ts
src/router/routes.ts
src/store/index.ts
tests/unit/App.spec.ts
tests/unit/ReviewConfirm.spec.ts

*Issue #:* /bcgov/entity#2958
* Updated the filing endpoint URLS to adapt to the recent back end changes.
* Added Draft flags to filing requests where required. 
* Removed the :key from router view and now correctly allowing VUE to handle refreshing the components.
* Implemented 'vuex-persistedstate' to handle storing State in between login redirects as well as refreshing the page. One request to fetch a draft filing is made when the app loads.
* Minor unit test fixes.
* Added auth required to the root level route '/' for the redirect to pick up before redirecting to/from '/define-company'
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license (Apache …

Incorporations draft refactor

---

src/App.vue
src/views/auth/Signin.vue

*Issue #:* /bcgov/entity#2894
Fix for when we access the root route with the nrNumber query param, it isn't properly passed through due to the redirect string format being a bit different.

2849 - update root route query param parsing

---

src/components/DefineCompany/OfficeAddresses.vue

*Issue #:* /bcgov/entity#3111
- Fix issue where address forms were not showing when using "same address" checkboxes, this was due to isSame checks being re-evaluated when the checkbox state changes and overriding the flags
- Updated logic to take into account first load and checkbox state changes after create

3111 - fix address inherited flags

---

src/components/AddPeopleAndRoles/ListPeopleAndRoles.vue
src/components/AddPeopleAndRoles/OrgPerson.vue
src/components/AddPeopleAndRoles/PeopleAndRoles.vue
src/components/DefineCompany/OfficeAddresses.vue
src/interfaces/index.ts
src/interfaces/stepper-interfaces/AddPeopleAndRole/org-person-interface.ts
src/interfaces/stepper-interfaces/AddPeopleAndRole/roles-array-interface.ts
src/mixins/filing-template-mixin.ts
src/store/getters/state-getters.ts
src/store/index.ts
tests/unit/App.spec.ts
tests/unit/ListPeopleAndRoles.spec.ts
tests/unit/OrgPerson.spec.ts
tests/unit/PeopleAndRoles.spec.ts

*Issue #:* /bcgov/entity#3134
* Removed the `Address` wrapping in the incorporations filings to match schema.
* Implemented a means of restoring the confirmEmail property when resuming a draft for better UX.
* Refactored `Persons` label into `Officer` to get in sync with the schema.
* Refactored the `Roles` property structure and means of identifying roles in the logic.
* Updated minor styling to align checkboxes.
* Updated Unit tests.

Business-Create Refactor to Sync to Schema Changes.

---

src/App.vue

*Issue #:* /bcgov/entity#3120
* Minor refactor in App.vue to no longer wait for a 'change' in entityType to trigger an update in the ui.
* Now initializes the UI based off entityType upon creation. 
**Notes**:
* We initially thought we would need to be reactive to the NR and entity type from within the incorporation flow but as things have developed it has been determined that info is determined and is required before starting the incorporation application. 

Updated EntityType Initializing

---

src/App.vue
src/components/Summary/SummaryDefineCompany.vue
src/components/common/EntityInfo.vue
src/components/common/NameRequestInfo.vue
src/components/common/index.ts
src/interfaces/store-interfaces/state-interfaces/name-request-interface.ts
src/mixins/name-request-mixin.ts
src/store/getters/state-getters.ts
src/store/index.ts
src/store/state/state-model.ts
src/views/DefineCompany.vue
tests/unit/DefineCompany.spec.ts
tests/unit/nameRequestInfo.spec.ts

*Issue #:* /bcgov/entity#2465
- Add in NameRequestInfo component
- Updated EntityInfo component to use NR Data
- Added helper function to create name request state from NR payload
- Updated review section to use NR Data for the company name
- Added name request data structure interfaces (NR details, NR applicant)
- Added in vuex getters for NR details/applicant, approved name
- Removed BCOMP, COOP, Reset buttons in Name request section in define company and updated tests
- Added Name request info component tests

2465 - Display NR Data

---

src/App.vue
src/router/index.ts
src/utils/axios-auth.ts
vue.config.js

*Issue #:* /bcgov/entity#3608
- added logic to catch error for token refresher failure and refresh the page ( an error is thrown if the refresh token has expired)
- updated keycloak config proxy url for local dev

3608 - handle token refresher failure

---

src/App.vue
src/mixins/name-request-mixin.ts

*Issue #:* /bcgov/entity#2332
While testing the subject ticket in Dev, I found that a response of HTTP 403 (Forbidden) can have useful errors/warning, so I updated the code to handle this.

display errors/warning in case of HTTP 403

---

package-lock.json
package.json
src/App.vue
src/components/AddPeopleAndRoles/OrgPerson.vue
src/components/AddPeopleAndRoles/PeopleAndRoles.vue
src/components/CreateShareStructure/ShareStructure.vue
src/components/DefineCompany/BusinessContactInfo.vue
src/components/DefineCompany/OfficeAddresses.vue
src/components/common/EntityInfo.vue
src/components/common/NameRequestInfo.vue
src/components/common/Stepper.vue
src/components/dialogs/ConfimRemoveDialog.vue
src/interfaces/stepper-interfaces/AddPeopleAndRole/add-people-role-interface.ts
src/interfaces/stepper-interfaces/CreateShareStructure/create-share-structure-interface.ts
src/interfaces/stepper-interfaces/DefineCompany/address-interface.ts
src/interfaces/stepper-interfaces/DefineCompany/define-company-interface.ts
src/mixins/common-mixin.ts
src/mixins/currency-lookup-mixin.ts
src/mixins/filing-template-mixin.ts
src/mixins/legal-api-mixin.ts
src/mixins/name-request-mixin.ts
src/schemas/office-address-schema.ts
src/store/state/state-model.ts
src/views/CreateShareStructure.vue
src/views/DefineCompany.vue
tests/unit/Actions.spec.ts
tests/unit/DefineCompany.spec.ts
tests/unit/PeopleAndRoles.spec.ts
tests/unit/ReviewConfirm.spec.ts
tests/unit/ShareStructure.spec.ts

*Issue #:* /bcgov/entity#3477
- updated app version to 0.4.0
- updated sbc-common-components import to 2.1.29 (non-readonly address
fields)
- cleaned up spaces around types
- cleaned up some indentations
- deleted obsolete imports, $refs, etc
- changed some divs to templates
- added missing case in updateAddress() that caused console logs
- added misc comments
- deleted redundant types in stateModel
- added method to set default address (country and region)
- updated misc unit tests

improved address UX re: country and province

---

public/config/configuration.json
src/utils/config-helper.ts

*Issue #:* /bcgov/entity#3764
- added in SBC_CONFIG_AUTH_API_URL to workaround user settings call URL with double slashes

3764 - work around for user settings call

---

src/views/IncorporationAgreement.vue

*Issue #:* /bcgov/entity#3716
The current doc path does not work in dev as the vue process path is different. So changing the doc url to leverage the base url value in session storage

Fixing the doc download path issue in dev

---

package-lock.json
package.json
src/App.vue
src/components/AddPeopleAndRoles/OrgPerson.vue
src/components/Summary/SummaryDefineCompany.vue
src/components/common/NameRequestInfo.vue
src/enums/nameRequestStates.ts
src/mixins/name-request-mixin.ts
tests/unit/nameRequestInfo.spec.ts

*Issue #:* /bcgov/entity#3946
- allow conditional NR if consent is received or waived
- if approved, get name whose state is "APPROVED"
- if conditional, get name whose state is "CONDITION"
- added case for waived consent flag
- added case for null consent flag
- misc lint fixes
- updated sbc-common-components dependency to 2.1.32
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).

handle consent received and consent waived states

---

src/App.vue

*Issue #:* /bcgov/entity#3764
On the initialization of a session there can be timing issues for CURRENT_ACCOUNT local storage property as it may not be populated in the local storage fast enough. Added an await next tick to give it time to populate into local storage.

3764 account info fix

---

src/App.vue
src/interfaces/filing-interfaces/filing-interface.ts
src/mixins/filing-template-mixin.ts
src/store/getters/state-getters.ts
src/store/index.ts
tests/unit/Actions.spec.ts
tests/unit/App.spec.ts

*Issue #:* /bcgov/entity#3962
- in a draft, allow nameRequest object without nrNumber
- always save nameRequest object with legalType
- make nrNumber and legalName optional
- removed unneeded fallback values
- added some handy getters
- update unit tests
- misc cleanup

handle nameRequest object for numbered business

---

src/main.ts

I just noticed this in the code. It looks like a work-around for testing that I forgot to remove before committing. (The other UI has the same code and redirects as intended.)
In summary, the app _should_ try to redirect to the Business Registry home page on error (after alerting the user).

restored redirect on app error

---

package-lock.json
package.json
src/components/DefineCompany/OfficeAddresses.vue
tests/unit/OfficeAddresses.spec.ts

*Issue #:* /bcgov/entity#4089
- version increment
- add logic to reset address to default when 'same as' checkboxes unchecked
- added a fix where records delivery address is not properly updated in some cases

4089 - update office addresses 'same as' logic

---

src/components/DefineCompany/BusinessContactInfo.vue
src/components/DefineCompany/OfficeAddresses.vue
tests/unit/OfficeAddresses.spec.ts

*Issue #:* /bcgov/entity#4156, /bcgov/entity#4151
Fixes and updates to step 1 so form validation errors show when a user resumes an application
*Office Addresses*
- added references to address components (sbc common component BaseAddress) so the form validate() function is accessible
- add checks on mounted to compare the default address state to what is loaded so re-validation can occur to show errors (e.g. non BC province)
- updated formValid() check to fix a bug where the validity for all addresses were not correct
*Business Contact*
- Added a default business contact object for comparison to re-evaluate validation (e.g. invalid email)
- Added check on mount to re-validate form if it is not the same as the default form state
By submitting this pull request, I …

4156, 4151

---

package-lock.json

- when npm prompts us (periodically), we need to run `npx browserslist@latest --update-db`
- this updates the package lock file, which is what I'm committing here

updated browsers list

---

package-lock.json
package.json
src/components/CreateShareStructure/ShareStructure.vue

*Issue #:* /bcgov/entity#8780
- Changed `maxNumberOfShares` and `parValue` to number

8780 - Changes for schema compliance - maxNumberOfShares and parValue

---

package-lock.json
package.json
src/components/CreateMemorandum/UploadMemorandum.vue
src/components/CreateMemorandum/UploadMemorandumSummary.vue
src/components/CreateRules/UploadRules.vue
src/components/CreateRules/UploadRulesSummary.vue
src/interfaces/index.ts
src/interfaces/stepper-interfaces/CreateMemorandum/create-memorandum-interface.ts
src/interfaces/stepper-interfaces/CreateRules/create-rules-interface.ts
src/interfaces/utils-interfaces/validation-detail-interface.ts
src/interfaces/utils-interfaces/validation-item-detail-interface.ts
src/mixins/common-mixin.ts
src/mixins/filing-template-mixin.ts
src/store/actions/actions-model.ts
src/store/getters/state-getters.ts
src/store/mutations/mutations-model.ts
src/store/state/state-model.ts
src/views/CreateMemorandum.vue
src/views/CreateRules.vue

*Issue #:* /bcgov/entity#8433
* moved `scrollToComponent` from component to page level for upload rules and upload memorandum components.  Note `scrollToComponent` can be probably moved to the root component(`App`) but have held off on doing this as I think it would make sense that if we decide to do this we would want to move all the other `scrollToComponent` calls to the `App` level.  
* update tooltip text and other component text based off of UXA feedback

8433 COOP IA upload memorandum - move scrollToComponent to page level, UI text updates

---

src/views/Incorporations/ReviewConfirm.vue

- Added whitespace styling in parent of DocumentDelivery component -- same for IA as for Dissolution.
- Updated font size to match other components on this page.
- No app version change this time.

Added whitespace styling in parent of DocumentDelivery component -- same for IA as for Dissolution.

---

package-lock.json
package.json
src/mixins/filing-template-mixin.ts
src/views/Dissolution/DissolutionReviewConfirm.vue

*Issue #:* /bcgov/entity#11237
* Remove redundant assignment of certify state when parsing DRAFT dissolution.
*Notes:* 
- This parsing of the draft filing always happens in the case of Incorporations and Dissolutions. 
- In this parsing, the certify state would be assigned but it was redundant as we assign the certifiedBy state from the Account ALWAYS. 
- Previously iteration must have worked as the draft was MOST LIKELY* assigned prior to our assignment in our `App.vue` but after a rework, the timing might have swapped. Subsequently overriding the properties from the account by the properties in an empty draft filing. 
- Another solution would be to assign the `certifiedBy` into the draft value from Filings UI where the Dissolution is created. 
By submitting …

Fixed CertifiedBy assignment

---

package-lock.json
package.json
src/App.vue
src/components/Dissolution/CompleteAffidavit.vue
src/components/Dissolution/CompleteResolution.vue
src/components/Dissolution/DissolutionStatement.vue
src/components/Incorporation/UploadMemorandum.vue
src/components/Incorporation/UploadRules.vue
src/components/common/AgreementType.vue
src/components/common/Stepper.vue
src/mixins/filing-template-mixin.ts
src/views/Dissolution/DissolutionAffidavit.vue
src/views/Dissolution/DissolutionDefineDissolution.vue
src/views/Dissolution/DissolutionResolution.vue
src/views/Incorporation/IncorporationAgreement.vue
src/views/Incorporation/IncorporationDefineCompany.vue
src/views/Incorporation/IncorporationMemorandum.vue
src/views/Incorporation/IncorporationPeopleRoles.vue
src/views/Incorporation/IncorporationRules.vue
src/views/Incorporation/IncorporationShareStructure.vue
src/views/Registration/RegistrationDefineBusiness.vue
src/views/Registration/RegistrationPeopleRoles.vue
tests/unit/UploadAffidavit.spec.ts

*Issue #:* /bcgov/entity#9518
- now set haveData in try{} instead of finally{}
- added some logging (temporary)
- replaced Vue.nextTick() with this.$nextTick()
- removed some unneeded "ignore changes"
- moved some "step validation" from created() to mounted()
- app version = 3.4.2

9518 cleanup and attempt to fix timing issues

---

package-lock.json
package.json
src/components/Registration/RegAddEditOrgPerson.vue
src/components/Registration/RegPeopleAndRoles.vue
src/components/common/ListPeopleAndRoles.vue
src/enums/roleTypes.ts
src/enums/ruleIds.ts
src/mixins/add-edit-org-person-mixin.ts
src/mixins/people-roles-mixin.ts
src/resources/Registrations/generalPartnership.ts
src/views/Registration/RegistrationReviewConfirm.vue
tests/unit/RegAddEditOrgPerson.spec.ts
tests/unit/RegPeopleAndRoles.spec.ts

*Issue #:* /bcgov/entity#10891
~This is ready to go except for some UI confirmations (or changes) from Yui.~ No changed needed atm.
- display delivery address for partners in list
- updated org label, blurb and confirm text
- business number is only for proprietor
- added roles checkbox for partner
- prompt delivery address also for partners
- added rule for num partners
- added buttons for adding partners
- added role type and rule for partner
- updated misc logic, getters, etc
- added some classnames for testing
- app version = 3.5.13

10891 Implemented P&R for General Partnerships

---

package-lock.json
package.json
src/components/Registration/BusinessTypeConfirm.vue
src/views/Registration/RegistrationDefineBusiness.vue
tests/unit/BusinessTypeConfirm.spec.ts

Issue #: [/bcgov/entity#9828](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/9828)
1. UXA notes from Yui
- Checkbox text in Step 1 needs size and line spacing adjustments. The referred "Certify" component is in Step 3.
- Spacing between the baseline of the last line of text to the thin grey line below is off by a couple of pixels. Use the Name Request Applicant subsection
2. Added BusinessTypeConfirm.spec.ts file for unit test

9828 Fix SP/GP Create UI - Step 1 - Business Type checkbox

---

package-lock.json
package.json
src/components/Dissolution/CompleteAffidavit.vue
src/components/Incorporation/UploadMemorandum.vue
src/components/Incorporation/UploadRules.vue
src/dialogs/PaymentErrorDialog.vue
tests/unit/PaymentErrorDialog.spec.ts

Issue #: [/bcgov/entity#9014](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/9014)
Description of changes:
When a payment error occurred, a popup window for "Unable to process payment" show up.
tags are included in the text in the popup window, and they need to be removed.
Issue #: [/bcgov/entity#11316](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/11316)
Description of changes:
Update help text for uploading mineo docs to advise people to leave a 1-inch margin at the top of their documents.
Business Type Confirm is now saved to a draft filing in the client side
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the …

9014/11316 HTML tags show up in the warning popup window/Create UI - CP Dissolution - Update text

---

src/mixins/date-mixin.ts
tests/unit/date-mixin.spec.ts

*Issue #:* https://github.com/bcgov/entity/issues/12384
Fixed the Date Mixin method that returned an invalid value if the user is not in Pacific timezone.

Bug: 12384

---

package-lock.json
package.json
src/resources/BreadCrumbResource.ts
src/services/business-lookup.services.ts
src/utils/config-helper.ts
src/utils/navigate.ts
tests/unit/App.spec.ts

*Issue #:* [/bcgov/entity#12529](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/12529)
- get account id from CURRENT_ACCOUNT 
- BreadCrumbResource.ts
- business-lookup.services.ts
- navigate.ts
- removed ACCOUNT_ID from config-helper.ts

12529 Create UI: get account id from CURRENT_ACCOUNT

---

package-lock.json
package.json
src/components/common/Stepper.vue

*Issue #:* /bcgov/entity#12759
- Validation for error styling now excludes review and confirm step until after file and pay is clicked
- App version = 4.0.23

12759 Fix incorrect error for review and confirm step of dissolution filing

---

package-lock.json
package.json
src/components/Dissolution/AssociationDetails.vue
src/views/DissolutionFirm/DissolutionFirm.vue
tests/unit/DissolutionFirm.spec.ts

*Issue #:* /bcgov/entity#12629
* fix date picker - first date available to pick is one day after the business founding date
* display text "Same as Mailing address" if Mailing address and Delivery address match in "Business Addresses" section
* fix dissolution date header - make the label turn red upon error validation

UX Fixes on dissolution dashboard

---

package-lock.json
package.json
src/components/common/Stepper.vue
tests/unit/Stepper.spec.ts

*Issue #:* /bcgov/entity#13372
- added "getValidateSteps" to the red cross icon validator.

13372 Create UI: Review and Confirm step icon should not show error until there is error

---

package-lock.json
package.json
src/components/common/BusinessContactInfo.vue

*Issue #:* /bcgov/entity#13371
- removed disabled for extension (updated requirement)
- reverted the code to before

13371 Create UI: Phone extension visual should remain "optional" until value entered

---

package-lock.json
package.json
src/components/Registration/RegAddEditOrgPerson.vue
src/components/Registration/RegPeopleAndRoles.vue
src/mixins/add-edit-org-person-mixin.ts
src/mixins/people-roles-mixin.ts

*Issue #:* /bcgov/entity/issues/13412
We want to keep the orgperson detail emplty in case of registration by a staff. So that staff will manually have to fill the information on behalf of the customer.

Feature 13412 - Allow Changing Completing Party in Registrations

---

package-lock.json
package.json
src/components/common/Actions.vue
tests/unit/Actions.spec.ts

*Issue #:* /bcgov/entity#13896
Note to consistently see this error you have to set throttling in dev tools
- Upon clicking Save and Resume and File Now removed setSaving to false because if the page is slow to redirect then the buttons become reenabled.
- App version = 3.8.13 -> 3.8.14
- Related PR [Edit UI](https://github.com/bcgov/business-edit-ui/pull/408)

13896 Pages should gray out after clicking Save and Resume Later and File Now, to avoid multiple clicks

---

package-lock.json
package.json
src/App.vue
src/components/Registration/RegPeopleAndRoles.vue
src/components/common/PeopleAndRoles.vue
src/mixins/people-roles-mixin.ts
src/rules/first-name-rules.ts
src/rules/middle-name-rules.ts
tests/unit/AddEditOrgPerson.spec.ts

*Issue #:* bcgov/entity#14119
This PR reverts the following change: https://github.com/bcgov/business-create-ui/pull/429
First commit:
- revert first name max length to 30
- revert middle name length to 30
- app version = 4.3.5
Second commit:
- bugfix: moved setCompletingParty after auth data is fetched (otherwise isRoleStaff is false)
- used direct getter for completing party's email

14119 Revert first name and middle name max lengths

---

package-lock.json
package.json
src/components/Incorporation/ShareStructure.vue
src/components/common/AddNameTranslation.vue
src/components/common/ListNameTranslations.vue
src/components/common/NameRequestInfo.vue
tests/unit/AddNameTranslation.spec.ts
tests/unit/ListNameTranslations.spec.ts
tests/unit/NameRequestInfo.spec.ts

*Issue #:* bcgov/entity#13345
- changed max name translation length to 50
- fixed actions column (auto)
- fixed row spacing
- misc cleanup
- app version = 4.3.11

13345 Fix name translation length + UI fixes

---

package-lock.json
package.json
src/App.vue
src/components/Dissolution/AssociationDetails.vue
src/components/Dissolution/CompleteResolution.vue
src/components/Incorporation/SummaryDefineCompany.vue
src/components/Incorporation/UploadMemorandum.vue
src/components/Incorporation/UploadRules.vue
src/components/Registration/DefineRegistrationSummary.vue
src/components/common/Actions.vue
src/components/common/EntityInfo.vue
src/components/common/NameRequestInfo.vue
src/dialogs/FileAndPayInvalidNameRequestDialog.vue
src/interfaces/store-interfaces/state-interface.ts
src/interfaces/store-interfaces/state-interfaces/name-request-interface.ts
src/mixins/filing-template-mixin.ts
src/mixins/name-request-mixin.ts
src/resources/BreadCrumbResource.ts
src/services/legal-services.ts
src/store/actions/actions-model.ts
src/store/getters/state-getters.ts
src/store/mutations/mutations-model.ts
src/store/state/state-model.ts
tests/unit/Actions.spec.ts
tests/unit/AgreementType.spec.ts
tests/unit/App.spec.ts
tests/unit/EntityInfo.spec.ts
tests/unit/FileAndPayInvalidNameRequestDialog.spec.ts
tests/unit/NameRequestInfo.spec.ts
tests/unit/filing-template-mixin.spec.ts

*Issue #:* bcgov/entity#14403
- log invalid NR message
- removed CCC/CC workaround (obsolete)
- removed generateNameRequestState()
- renamed getApprovedName -> getNrApprovedName
- removed getNameRequestDetails
- removed getNameRequestApplicant
- simplified/cleaned up NameRequestInfo.vue
- cleaned up NR interfaces to make actual data
- used NR types in mixin, service, etc
- updated isNrValid()
- app version = 4.3.19

14403 Cleaned up NR handling

---

package-lock.json
package.json
src/components/common/AddNameTranslation.vue
src/components/common/ListNameTranslations.vue
tests/unit/AddNameTranslation.spec.ts

*Issue #:* /bcgov/entity#14545
Corresponding PR in Edit UI https://github.com/bcgov/business-edit-ui/pull/433
- corp name translation input is now capitalized.
- add unit test for name translation input being capitalized.
- align AddNameTranslation.vue component and the unit tests to the Edit UI
- App version 4.4.2 -> 4.4.3

14545 Upper case display for Corp Name Translation

---

package-lock.json
package.json
src/components/common/Actions.vue
src/mixins/filing-template-mixin.ts
src/store/getters/state-getters.ts
src/views/Incorporation/IncorporationReviewConfirm.vue
tests/unit/Actions.spec.ts
tests/unit/IncorporationReviewConfirm.spec.ts
tests/unit/filing-template-mixin.spec.ts
tests/unit/test-data/incorpApp.json

*Issue #:* /bcgov/entity#14789
Fix bug that caused schema error when submitting an incorporation application without a court order.
Here's the relevant snippet of the payload that was causing the error:
```    
"courtOrder": {
"fileNumber": "",
"hasPlanOfArrangement": false
}
```
The fix removes the "courtOrder" attribute unless either the fileNumber is populated or "hasPlanOfArrangement" is true.

14789 Create UI throwing schema error when court order is not entered

---

package-lock.json
package.json
src/components/common/AddEditOrgPerson.vue
src/components/common/OfficeAddresses.vue
src/mixins/filing-template-mixin.ts
src/views/Incorporation/IncorporationDefineCompany.vue

*Issue #:* /bcgov/entity#14788
When a user starts any IA filing say for ex a ULC filing and then hit on Save and Resume, Now upon returning and resuming the filing from the draft state the entered Records office addresses aren't being saved.

14788 Save and resume IA not saving the Records office info

---

package-lock.json
package.json
src/components/common/AddEditOrgPerson.vue
src/components/common/PeopleAndRoles.vue
src/components/common/RegAddEditOrgPerson.vue
src/components/common/RegPeopleAndRoles.vue
src/interfaces/filing-interfaces/filing-interfaces.ts
src/interfaces/stepper-interfaces/AddPeopleAndRole/people-and-roles-resource-interface.ts
src/interfaces/store-interfaces/state-interfaces/restoration-state-interface.ts
src/mixins/add-edit-org-person-mixin.ts
src/mixins/filing-template-mixin.ts
src/mixins/people-roles-mixin.ts
src/resources/Incorporation/BC.ts
src/resources/Incorporation/BEN.ts
src/resources/Incorporation/CC.ts
src/resources/Incorporation/ULC.ts
src/resources/Restoration/BC.ts
src/resources/Restoration/BEN.ts
src/resources/Restoration/CC.ts
src/resources/Restoration/ULC.ts
src/store/state/resource-model.ts
src/views/Registration/RegistrationPeopleRoles.vue
src/views/Restoration/RestorationApplicantInformation.vue
tests/unit/AddEditOrgPerson.spec.ts
tests/unit/RegAddEditOrgPerson.spec.ts
tests/unit/RegPeopleAndRoles.spec.ts

*Issue #:* bcgov/entity#14798
- reverted restoration changes from IA people and roles components
- added restoration changes to Reg people and roles components
- fixed misc layout and component ids
- moved RegXXX (people and roles components) from components/Registration/ to components/common/
- changed restoration to use RegXXX components (which support business lookup)
- app version = 4.5.5

14798 Changed restorations to use "registration" people-roles components + misc updates (incremental)

---

package-lock.json
package.json
src/views/Dissolution/DissolutionReviewConfirm.vue
src/views/DissolutionFirm/DissolutionFirm.vue
src/views/Incorporation/IncorporationReviewConfirm.vue

*Issue #:* /bcgov/entity14964
The **shared** component CourtOrderPoa has been updated.  This small change updates CourtOrderPoa to the latest version and set the prop `courtOrderNumberRequired` to false when calling the component.

14964 - bump CourtOrderPoa to v3.0.0

---

package-lock.json
package.json
src/components/common/ListPeopleAndRoles.vue
src/components/common/RegAddEditOrgPerson.vue
src/components/common/RegPeopleAndRoles.vue
src/interfaces/filing-interfaces/filing-interfaces.ts
src/interfaces/stepper-interfaces/AddPeopleAndRole/people-and-roles-resource-interface.ts
src/interfaces/store-interfaces/state-interfaces/restoration-state-interface.ts
src/mixins/filing-template-mixin.ts
src/resources/Restoration/BC.ts
src/resources/Restoration/BEN.ts
src/resources/Restoration/CC.ts
src/resources/Restoration/ULC.ts
src/store/actions/actions-model.ts
src/store/mutations/mutations-model.ts
src/store/state/state-model.ts

*Issue #:* bcgov/entity#14798
- updated people and roles list header
- added fallback "not registered in BC" text
- added fallback confirm checkbox text
- added fallback "registered in BC" text
- added subheader resource for Add People And Roles component
- removed `restoration.date` property (see https://github.com/bcgov/business-schemas/pull/125)
- app version = 4.5.14

14798 UI updates

---

.env.example
.gitignore
devops/vaults.env
package-lock.json
package.json
src/mixins/date-mixin.ts
src/utils/FetchConfig.ts
vue.config.js

*Issue #:* [15499](https://github.com/bcgov/entity/issues/15499)
The current VUE_APP_PATH of GCP CD setting cause a null value exception after deploy to firebase. It must be changed to "/" value to avoid exception.
Also, open a ticket to investigate BASE_URL issue. https://github.com/bcgov/entity/issues/15817

Fixed the content path issue.

---

package-lock.json
package.json
src/App.vue
src/components/Dissolution/AssociationDetails.vue
src/mixins/filing-template-mixin.ts
src/store/store.ts

*Issue #:* bcgov/entity#16175
- app version = 5.2.1
- deleted setEntityName and used setLegalName instead
- deleted getBusiness and used getBusinessOfficeAddress instead
- fixed undefined legal name -- added fallback for parsing draft without legal name (or legal type or founding date)

16175 Fixed undefined legal name in a dissolution (and also restoration)

---

package-lock.json
package.json
src/interfaces/filing-interfaces/filing-interfaces.ts
src/mixins/filing-template-mixin.ts

*Issue #:* bcgov/entity#16375
- app version = 5.2.4
- don't save legal name in restoration business object

16375 fix "None is not a String" filing error

---

package-lock.json
package.json
src/components/Dissolution/CompleteResolution.vue

*Issue #:* ops-support # 3105
- app version = 5.4.2a
- fixed previewImageSource()

ops-support-3105 Fixed previewImageSource()

---

package-lock.json
package.json
src/components/Restoration/RestorationType.vue
src/views/Restoration/RestorationBusinessName.vue

*Issue #:* /bcgov/entity#15863
- Added v-divider separating line to distinguish between approval type and restoration type. 

15863 dividing line approval type

---

package-lock.json
package.json
src/App.vue
src/components/Dissolution/AssociationDetails.vue
src/interfaces/filing-interfaces/filing-interfaces.ts
src/interfaces/store-interfaces/state-interfaces/business-interface.ts
src/mixins/filing-template-mixin.ts
src/store/state/state-model.ts
src/store/store.ts

*Issue #:* /bcgov/entity#17216
Show start date for a firm dissolution filing
Business start date in Business info section:
Before:
After:
Note: Dissolution date rules do not need to be updated. It is working as expected. Confirmed with Mihai.

17216 - Show start date for a firm dissolution filing 

---

package-lock.json
package.json
src/App.vue

*Issue #:* /bcgov/entity#18102
- fixed typo to show full legal name of account holder at Certify for IAs
- app version = 5.5.6

18102 Show full legal name of the account holder at Certify when filing IA

---

package-lock.json
package.json
src/rules/date-rules.ts
src/views/DissolutionFirm/DissolutionFirm.vue
tests/unit/DissolutionFirm.spec.ts

*Issue #:* /bcgov/entity#18008
- Fixed the bug in which the UI doesn't let the user select a dissolution date that is the same as the registration date.

Fixed Dissolution Date bug

---

package-lock.json
package.json
src/App.vue
src/components/Restoration/BusinessName.vue
src/components/common/Actions.vue
src/services/legal-services.ts
tests/unit/Actions.spec.ts
tests/unit/App.spec.ts
tests/unit/BusinessName.spec.ts

*Issue #:* /bcgov/entity#17160
Add a new fetch Name Request service ( call legal-api - validate the email and phone )

17160 Update fetchNr with phone and email validation

---

package-lock.json
package.json
src/components/Amalgamation/AmalgamatingBusinesses.vue
src/interfaces/store-interfaces/state-interfaces/amalgamation-state-interface.ts
src/store/state/state-model.ts
src/store/store.ts
src/views/AmalgamationRegular/Information.vue

*Issue #:* /bcgov/entity#18535
- Added the Amalgamating Businesses Part 1
https://github.com/bcgov/business-create-ui/assets/122301442/92f4337b-9536-44de-8e94-6b850b811062

18535 - Add Amalgamating Businesses Part 1

---

package-lock.json
package.json
src/assets/styles/theme.scss
src/components/Amalgamation/AmalgamatingBusinesses.vue
src/components/Amalgamation/BusinessStatus.vue
src/components/Amalgamation/BusinessTable.vue
src/components/index.ts
src/enums/businessStatuses.ts
src/enums/index.ts
src/interfaces/filing-interfaces/filing-interfaces.ts
src/interfaces/store-interfaces/state-interfaces/amalgamation-state-interface.ts
src/main.ts
src/mixins/filing-template-mixin.ts
src/store/state/state-model.ts
src/store/store.ts
src/views/AmalgamationRegular/Information.vue

*Issue #:* bcgov/entity#18640
- app version = 5.6.5
- removed unnecessary re-export
- added initial BusinessTable component
- renamed property in amalg interface
- updated filing save/restore
- added global warning (orange) colour
- added Business Status sub-component
- added basic functionality to table
- added Business Statuses enum
- added businesses table to store (with default data for now only)
- added initial validation code

18640 Amalgamating business table (initial)

---

package-lock.json
package.json
src/components/Amalgamation/AmalgamatingBusinesses.vue
src/components/Amalgamation/BusinessStatus.vue
src/components/Amalgamation/BusinessTable.vue
src/enums/amalgamationEnums.ts
src/enums/businessStatuses.ts
src/enums/index.ts
src/interfaces/store-interfaces/state-interfaces/amalgamation-state-interface.ts
src/store/state/state-model.ts
src/store/store.ts
tests/unit/BusinessName.spec.ts
tests/unit/NameRequestInfo.spec.ts
tests/unit/NameTranslations.spec.ts
tests/unit/ShareStructure.spec.ts

*Issue #:* bcgov/entity#18640
- app version = 5.6.6
- worked on amalgamating businesses data/types
- renamed some enums
- fixed table key
- added more BusinessTable logic (including foreign jurisdiction)
- updated static (test) data
- updated some imports in unit tests

18640 Amalgamating businesses structure + validations + etc

---

package-lock.json
package.json
src/components/Amalgamation/AmalgamatingBusinesses.vue
src/interfaces/store-interfaces/state-interfaces/amalgamation-state-interface.ts
src/services/business-lookup-services.ts
src/store/state/state-model.ts
src/store/store.ts
tests/unit/business-lookup-services.spec.ts

*Issue #:* /bcgov/entity#18535
- Continuation of Amalgamating Businesses part 1
- Updated business lookup to search only for: A, BEN, CC, BC, and ULC
- Refactored the saveAmalgamatingBusiness to make parallel calls + added email fetching
- Setting the AmalgamatingBusiness component validation (store getter and setter)

18535 Amalgamating Businesses Part 1 Continuation

---

package-lock.json
package.json
src/components/Amalgamation/AmalgamatingBusinesses.vue
src/interfaces/filing-interfaces/filing-interfaces.ts
src/mixins/filing-template-mixin.ts
src/store/store.ts

*Issue #:* /bcgov/entity#18535
- Save and resume draft Amalgamation Filing

18535 - Save and Resume Draft Amalgamation

---

package-lock.json
package.json
src/components/Amalgamation/AmalgamatingBusinesses.vue
src/components/Amalgamation/BusinessTable.vue
src/interfaces/store-interfaces/state-interfaces/amalgamation-state-interface.ts
src/mixins/amalgamation-mixin.ts
src/mixins/index.ts
src/store/store.ts
src/views/AmalgamationRegular/Information.vue
src/views/AmalgamationRegular/ReviewConfirm.vue
src/views/Incorporation/IncorporationDefineCompany.vue

*Issue #:* bcgov/entity#18640
- app version = 5.6.10
- updated some validity calculations
- moved ting validations to a mixin
- generalized status computation
- updated regular amalgation validity
- updated to use temp copy of array (instead of local copy)

18640 Incremental amalgamating businesses validations, etc

---

package-lock.json
package.json
src/App.vue
src/components/Amalgamation/AmalgamatingBusinesses.vue
src/components/Amalgamation/BusinessStatus.vue
src/components/Amalgamation/BusinessTable.vue
src/components/Amalgamation/BusinessTableSummary.vue
src/enums/amalgamationEnums.ts
src/interfaces/store-interfaces/state-interfaces/amalgamation-state-interface.ts
src/mixins/amalgamation-mixin.ts
src/services/legal-services.ts
src/store/state/state-model.ts
src/store/store.ts
tests/unit/legal-services.spec.ts

*Issue #:* bcgov/entity#18640
Commit 1:
- app version = 5.6.11
- imported latest BusinessLookup shared component
- updated fetchBusinessInfo return object
- simplified Amalg Businesses button and panel logic
- added Cancel button to Foreign panel
- added snackbar for save business errors
- deleted debugging template code
Commit 2:
- added fetch for business filings (for more validations)
- renamed AmalgamatingStatuses -> AmlStatuses
- added AmlTypes enum and replaced strings
- added some properties to TING business object (for more validations)
- added LegalServices.fetchFilings()
- misc updates
Commit 3:
- changed all to allSettled so I can get partial fetches
- fall back to lookup properties if some fetches fail (eg, not amalgamated)
- added empty table message …

18640 More amalgamating fetch / validations work

---

src/components/Amalgamation/AmalgamatingBusinesses.vue
src/mixins/amalgamation-mixin.ts
src/mixins/filing-template-mixin.ts

*Issue #:* /bcgov/entity#18960
Re-fetch the amalgamating businesses information when loading draft.
https://github.com/bcgov/business-create-ui/assets/122301442/c3e28dfc-23cc-4875-a572-00bb34e84eb2

18960 - Re-fetch businesses information when loading draft

---

src/components/Amalgamation/AmalgamatingBusinesses.vue

*Issue #:* /bcgov/entity#18722
- Update foreign company error messages

18722 Update foreign company error messages

---

package-lock.json
package.json
src/resources/AmalgamationRegular/BC.ts
src/resources/AmalgamationRegular/BEN.ts
src/resources/AmalgamationRegular/CC.ts
src/resources/AmalgamationRegular/ULC.ts

*Issue #:* /bcgov/entity#18847
update certify text for amalgamations

18847 - update certify text for amalgamations

---

package-lock.json
package.json
src/components/Amalgamation/AmalgamatingBusinesses.vue

*Issue #:* /bcgov/entity#18722
- Corporate name field should have a 150 character limit
- Corporate number field should have a 40 character limit and disallow no space
- Corporate number field should be optional if the home jurisdiction is not part of the MRAS list

18722 - Update foreign business validation rules

---

package-lock.json
package.json
src/store/store.ts
src/views/AmalgamationRegular/ReviewConfirm.vue

*Issue #:* /bcgov/entity#18848
Add court order / POA component (only for staff)
Invalid Court order:
On clicking File and Pay/ step validity

18848 - add court order / POA component on review page

---

package-lock.json
package.json
src/mixins/filing-template-mixin.ts

*Issue #:* bcgov/entity#18788
- app version = 5.6.21
- added fallback for drafts created without Correct Name Option

18788 Added fallback

---

package-lock.json
package.json
src/components/Amalgamation/BusinessTable.vue
src/components/Amalgamation/BusinessTableSummary.vue
tests/unit/BusinessStatus.spec.ts
tests/unit/BusinessTable.spec.ts
tests/unit/BusinessTableSummary.spec.ts

*Issue #:* bcgov/entity#18641
- app version = 5.6.28
- misc fixes
- added Business Status unit tests
- added Business Table unit tests
- added Business Table Summary unit tests

18641 Business table unit tests

---

package-lock.json
package.json
src/views/AmalgamationRegular/ReviewConfirm.vue

*Issue #:* /bcgov/entity#18689
- Fix Certify blocked being valid even if the box hasn't been ticked

Fixed bug with certify if submitting the amalgamation failed

---

package-lock.json
package.json
src/components/Amalgamation/BusinessStatus.vue
src/mixin-tester.vue
src/mixins/amalgamation-mixin.ts
tests/unit/BusinessStatus.spec.ts
tests/unit/BusinessTable.spec.ts
tests/unit/amalgamation-mixin.spec.ts
tests/unit/filing-template-mixin.spec.ts
tests/vitest-wrapper-factory.ts

*Issue #:* bcgov/entity#18641
- app version = 5.6.32
- added Amalgamation Mixin unit tests
- updated some status messages (per Yui)
- updated some rules (per Yui)
- added more Business Table unit tests (disabled until future)
- misc updates

18641 More unit tests

---

package-lock.json
package.json
src/components/common/Stepper.vue

*Issue #:* /bcgov/entity#19224
This PR should be in the Guinness World Records for smallest PR ever 😆 
For points 1 and 3 in the ticket, I've tested and they seem to be working. They might've been fixed collaterally maybe?
- For point 1: The state icons on the first step is missing when validation is triggered.
https://github.com/bcgov/business-create-ui/assets/122301442/66c3fb75-5d96-42e2-8b32-c17bdacd2c32
- For point 3: The valid step states do not persist their green checkmark state when draft is closed and reopened. This works on IA filing. I.e. in IA, if share structure is added and has green checkmark, when the user saves the draft and comes back to it, the green checkmark on the valid step displays on load. …

Amalgamation stepper fix

---

package-lock.json
package.json
src/components/Amalgamation/AmalgamatingBusinesses.vue
src/components/Amalgamation/BusinessTable.vue
src/mixins/amalgamation-mixin.ts
src/views/Amalgamation/Information.vue
tests/unit/AmalgamatingBusinesses.spec.ts
tests/unit/BusinessTable.spec.ts

*Issue #:* bcgov/entity#19036
- app version = 5.8.1
- added checklist section + computeds
- changed Business Table "valid" to "allOk"
- refactored Amalgamating Businesses validation
- cleaned up Information page layout
- fixed bug where holding company is changed to amalgamating
- updated unit tests (fixes to come in a future PR)

19036 Added "must include" checklist + refactored validation

---

.eslintrc.js
package-lock.json
package.json
src/App.vue
src/components/Amalgamation/AmalgamatingBusinesses.vue
src/components/Amalgamation/BusinessTable.vue
src/components/Amalgamation/BusinessTableSummary.vue
src/components/Amalgamation/ResultingBusinessName.vue
src/components/common/Actions.vue
src/components/common/BusinessContactInfo.vue
src/components/common/ListNameTranslations.vue
src/interfaces/store-interfaces/state-interfaces/amalgamation-state-interface.ts
src/mixins/amalgamation-mixin.ts
src/mixins/document-mixin.ts
src/mixins/filing-template-mixin.ts
src/rules/phone-rules.ts
src/services/legal-services.ts
src/views/Amalgamation/BusinessInfo.vue

*Issue #:* bcgov/entity#19037
**I'm presently working on the unit tests, but I think all the functionality is complete and working correctly.**
- added eslint rule
- app version = 5.8.4
- fixed parseAmalgamationDraft to async
- added code for new holding/primary business
- now save TING complete addresses
- updated tables to show reg office mailing address
- don't show actions menu for holding/primary business
- added more actions menu only for short-form amalgamating businesses
- make business table reactive to holding/primary change
- update prepopulated data on file and pay
- fixed Business Contact Info reactivity bug
- opened name translations sub-menu to the left (per Yui)
- now return the holding/primary business from refetchAmalgamatingBusinessesInfo()
- …

19037 Added processing for new holding/primary company

---

package-lock.json
package.json
src/components/Amalgamation/AmalgamatingBusinesses.vue
src/components/Amalgamation/BusinessTable.vue
src/components/Amalgamation/BusinessTableSummary.vue
src/interfaces/store-interfaces/state-interfaces/amalgamation-state-interface.ts
src/mixins/amalgamation-mixin.ts
tests/unit/AmalgamatingBusinesses.spec.ts
tests/unit/BusinessTable.spec.ts
tests/unit/BusinessTableSummary.spec.ts

*Issue #:* /bcgov/entity#19561
- corpNumber -> identifier in foreign amalgamating business to reflect the latest schema change

19561 corpNumber to identifier in foreign amalgamating business

---

package-lock.json
package.json
src/components/Amalgamation/BusinessTable.vue
src/components/Amalgamation/ResultingBusinessName.vue

*Issue #:* bcgov/entity#19629
- app version = 5.8.6
- imported latest shared correct-name components
- pass in null entity type so it's not checked
- if adopting a business' name, also adopt its legal type
- when using a new NR, also use its legal type
Also, a bugfix from bcgov/entity#19037:
- only show more actions menu for LEAR businesses

19629 Update legal type when adopting a business' name or new NR

---

package-lock.json
package.json
src/App.vue
src/components/Amalgamation/ResultingBusinessName.vue
src/components/common/Actions.vue
src/components/common/EffectiveDateTime.vue
src/components/common/SummaryDefineCompany.vue
src/main.ts
src/mixins/amalgamation-mixin.ts
src/mixins/common-mixin.ts
src/mixins/filing-template-mixin.ts
src/resources/AmalgamationRegular/BC.ts
src/resources/AmalgamationRegular/BEN.ts
src/resources/AmalgamationRegular/CC.ts
src/resources/AmalgamationRegular/ULC.ts
src/resources/AmalgamationShort/BC.ts
src/resources/AmalgamationShort/BEN.ts
src/resources/AmalgamationShort/CC.ts
src/resources/AmalgamationShort/ULC.ts
src/store/store.ts
src/views/Amalgamation/BusinessInfo.vue
src/views/Amalgamation/ReviewConfirm.vue
tests/unit/AmalgamationBusinessInfo.spec.ts
tests/unit/AmalgamationInformation.spec.ts
tests/unit/AmalgamationPeopleRoles.spec.ts
tests/unit/AmalgamationReviewConfirm.spec.ts
tests/unit/AmalgamationShareStructure.spec.ts

*Issue #:* bcgov/entity#19041
**This is a partial commit for the ticket, but it contains some useful fixes that I'd like merged asap.**
- app version = 5.8.8
- deleted useless isViteRunning getter (was only used in 1 place)
- changed re-routing code to not push the wrong route to history
- update misc comments
- **fixed** invalid date error in EffectiveDateTime
- **fixed** resources not updated when holding/primary business changes
- **fixed** amalgamation statement validation (was undefined on draft restore)
- updated certify statements (for regular and short-form amalgamations)
- **fixed** isAmalgamationInformationValid()
- **fixed** amalgamation validation (ignore share structure validity for short-form amalg)
- refactored Business Info test suite to handle …

19041 Finished validations + updated certify statements + updated unit tests

---

package-lock.json
package.json
src/resources/AmalgamationRegular/BC.ts
src/resources/AmalgamationRegular/BEN.ts
src/resources/AmalgamationRegular/CC.ts
src/resources/AmalgamationRegular/ULC.ts
src/resources/AmalgamationShort/BC.ts
src/resources/AmalgamationShort/BEN.ts
src/resources/AmalgamationShort/CC.ts
src/resources/AmalgamationShort/ULC.ts
src/resources/ContinuationIn/BC.ts
src/resources/ContinuationIn/BEN.ts
src/resources/ContinuationIn/CC.ts
src/resources/ContinuationIn/ULC.ts
src/resources/Dissolution/BC.ts
src/resources/Dissolution/BEN.ts
src/resources/Dissolution/CC.ts
src/resources/Dissolution/ULC.ts
src/resources/Incorporation/BC.ts
src/resources/Incorporation/BEN.ts
src/resources/Incorporation/CC.ts
src/resources/Incorporation/ULC.ts
src/resources/ResourcePhrases.ts

*Issue #:* bcgov/entity#19041
- app version = 5.8.9
- created constants (enum) for common resource phrases
- updated misc resource files to use constants

19041 Created constants (enum) for resource phrases

---

package-lock.json
package.json
src/mixins/amalgamation-mixin.ts

*Issue #:* bcgov/entity#19041
- app version = 5.8.10
- added validation for business not part of a FE amalgamation

19041 Added validation for business not part of a FE amalgamation

---

package-lock.json
package.json
src/mixins/filing-template-mixin.ts

*Issue #:* bcgov/entity#19774
- app version = 5.8.11
- delete officer email if it's null

19774 Fixed null officer email schema error

---

package-lock.json
package.json
src/resources/AmalgamationRegular/BC.ts
src/resources/AmalgamationRegular/BEN.ts
src/resources/AmalgamationRegular/CC.ts
src/resources/AmalgamationRegular/ULC.ts
src/resources/AmalgamationShort/BC.ts
src/resources/AmalgamationShort/BEN.ts
src/resources/AmalgamationShort/CC.ts
src/resources/AmalgamationShort/ULC.ts

*Issue #:* bcgov/entity#19754
- app version = 5.8.13
- removed redundant first certify bullet
- set certify entity display to "business"

19754 Update amalgamation resources for Certify component

---

package-lock.json
package.json
src/components/Amalgamation/ResultingBusinessName.vue
tests/unit/ResultingBusinessName.spec.ts

*Issue #:* bcgov/entity#19745
- app version = 5.8.14
- imported updated correct-name shared component
- now filter adoptee businesses here instead of in shared component
- added filter for entity type
- added test suite

19745 Implemented compatible entity type check for adoptee businesses

---

package-lock.json
package.json
src/App.vue
src/mixins/amalgamation-mixin.ts
src/resources/BreadcrumbResource.ts
src/services/auth-services.ts
src/services/business-lookup-services.ts
src/services/legal-services.ts
src/store/store.ts
src/utils/Navigate.ts
tests/unit/App.spec.ts

*Issue #:* bcgov/entity#19698
- app version = 5.8.15
- added get after set to update store
- added check for empty auth info when re-fetching ting business info
- added some safety checks when updating prepopulated data (ie, new holding/primary business)
- moved accountId computed to store
- added Account-Id header to fetchAuthInfo()
- deleted some unused getters/local code
- cleaned up some App unit tests

19698 Added Account-Id to auth api call + check for null auth info + small cleanup

---

package-lock.json
package.json
tests/unit/AmalgamatingBusinesses.spec.ts
tests/unit/AmalgamationInformation.spec.ts
tests/unit/AmalgamationPeopleRoles.spec.ts
tests/unit/AmalgamationReviewConfirm.spec.ts
tests/unit/AmalgamationShareStructure.spec.ts
tests/unit/PeopleAndRoles.spec.ts

*Issue #:* /bcgov/entity#19044
Added unit tests in:
- AmalgamationBusinessInfo.spec.ts
- AmalgamationInformation.spec.ts
- AmalgamationPeopleRoles.spec.ts
- AmalgamationReviewConfirm.spec.ts
- PeopleAndRoles.spec.ts

19044 - Amalgamation unit tests

---

package-lock.json
package.json
src/components/Amalgamation/AmalgamatingBusinesses.vue
src/components/common/ListPeopleAndRoles.vue
src/mixins/filing-template-mixin.ts

*Issue #:* bcgov/entity#19750
- app version = 5.9.2
- fixed error handling bug (missing await)
- removed unneeded code in buildAmalgamationFiling()
- updated some comments

19750 Fixed error handling

---

package-lock.json
package.json
src/mixins/filing-template-mixin.ts

*Issue #:* bcgov/entity#19856
- app version = 5.9.3
- delete officer email property if it's empty ("")

19856 Fixed empty officer email schema issue

---

package-lock.json
package.json
src/components/common/Actions.vue
src/mixins/amalgamation-mixin.ts
src/mixins/filing-template-mixin.ts

*Issue #:* bcgov/entity#19756
- app version = 5.9.4
- updated some code comments
- on draft resume, update prepopulated data after the legal name is restored (as we may override it)

19756 Small change so prepopulated data overrides legal name

---

package-lock.json
package.json
src/components/Amalgamation/AmalgamatingBusinesses.vue
tests/unit/AmalgamatingBusinesses.spec.ts

*Issue #:* bcgov/entity#19897
- app version = 5.9.6
- save region value instead of text (x2)
- fixed unit test

19897 Fixed foreign jurisdiction region

---

package-lock.json
package.json
src/resources/BreadcrumbResource.ts

*Issue #:* bcgov/entity#19906
- app version = 5.9.8
- updated My Business Registry breadcrumb
- updated Staff dashboard breadcrumb

19906 Updated breadcrumbs

---

package-lock.json
package.json
src/views/Incorporation/IncorporationReviewConfirm.vue
tests/unit/IncorporationReviewConfirm.spec.ts

*Issue #:* /bcgov/entity# 21241
- Hided Court Order and POA components for users

21241 - Hide Court Order and POA for Users

---

package-lock.json
package.json
src/components/ContinuationIn/ContinuationAuthorization.vue

*Issue #:* bcgov/entity#21248
- app = 5.10.16
- initialized rest of Continuation Authorization object variable so they are reactive

21248 Fixed continuation authorization reactivity issue

---

package-lock.json
package.json
src/components/ContinuationIn/ContinuationAuthorization.vue
src/components/ContinuationIn/ExtraproRegistration.vue
src/components/ContinuationIn/ManualBusinessInfo.vue

*Issue #:* bcgov/entity#21310
Commit 1:
- app version = 5.10.20
- added Authorization Date min date validation
Commit 2:
- trimmed whitespace from text input fields
- now deep-watch objects
*Screenshots:*
Minimum date is May 16, 2001 because that's the date of registration in BC.
Minimum date is Jan 15, 20024 because that's the date of incorporation in home jurisdiction.

21310 Implement Authorization Date min date validation

---

package-lock.json
package.json
src/components/ContinuationIn/ContinuationAuthorization.vue
src/components/ContinuationIn/UploadAffidavit.vue
src/components/Dissolution/CompleteAffidavit.vue
src/components/Incorporation/UploadMemorandum.vue
src/components/Incorporation/UploadRules.vue
src/mixins/document-mixin.ts

*Issue #:* bcgov/entity#21110
**This is part 1 of the ticket (when user clears an uploaded file). Part 2 will be in a separate PR. Unfortunately this isn't testable at the moment because the Legal API endpoint doesn't exist, but it can be verified that this code change doesn't break anything. I will test when I work on part 2.**
- app version = 5.10.24
- added document deletion to Continuation Authorization
- added document deletion to Upload Affidavit
- added document deletion to Complete Affidavit
- added document deletion to Upload Memorandum
- added document deletion to Upload Rules
- added deleteDocument() method
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the …

21110 Deleted documents that were cleared by user

---

package-lock.json
package.json
src/components/Amalgamation/ResultingBusinessName.vue
src/components/common/MessageBox.vue
src/components/common/NameRequestInfo.vue
src/components/common/SummaryDefineCompany.vue
tests/unit/NameRequestInfo.spec.ts

*Issue #:* bcgov/entity#21894
- app version = 5.11.3
- imported latest correct-name shared component
- added CCC and CUL to numbered company suffix logic (2 places)
- added "LTD." to CCC numbered name (2 places)
- pass entity type to CorrectName so it can correctly show numbered name
- updated/added unit tests

21894 Added LTD to CCC numbered name

---

package-lock.json
package.json
src/views/Amalgamation/BusinessInfo.vue
src/views/ContinuationIn/ContinuationInBusinessBc.vue

*Issue #:* /bcgov/entity#19483
- Changed the word "businesses" from Plural to Singular, now:  "... Office Mailing and Delivery Addresses of the resulting **business**..." for Amalg and ContIn

Fix-19483-Amalg/ContIn-Singular-Grammar

---

package-lock.json
package.json
src/views/Amalgamation/ReviewConfirm.vue
src/views/ContinuationIn/ContinuationInReviewConfirm.vue
src/views/Dissolution/DissolutionReviewConfirm.vue
src/views/DissolutionFirm/DissolutionFirm.vue
src/views/Incorporation/IncorporationReviewConfirm.vue
src/views/Registration/RegistrationReviewConfirm.vue

*Issue #:* /bcgov/entity#22845
- For the review & confirm page, updated the Documents Delivery Section:
Made the Completing Party email address editable
Keep prepopulating the default staff email address
- Only when it's a staff filing
- Updated for Amalgamation, Dissolution, Continuation, Incorporation, Registration. 
- Restoration seems not needed/ not updated.

22845 -  Update Confirm Page Delivery Email

---

package-lock.json
package.json
src/components/Restoration/ApprovalType.vue
src/components/Restoration/RestorationType.vue
src/views/Restoration/RestorationBusinessName.vue

*Issue #:* bcgov/entity#15538
- app version = 5.11.20
- imported latest shared Approval Type component
- fixed approval type layout
- refactored approval type validation
- refactored restoration type validation
- fixed restoration business name layout

15538 Fixed restoration type layout and validation issues

---

package-lock.json
package.json
src/components/Restoration/ApprovalType.vue
src/views/Restoration/RestorationBusinessName.vue

*Issue #:* bcgov/entity#15538
- app version = 5.11.21
- added court order initial case
- fixed registrar initial case
- fixed lint warning

15538 Fixed court order type not being restored

---

package-lock.json
package.json
src/components/ContinuationIn/ContinuationAuthorization.vue

*Issue #:* bcgov/entity#22995
- app version = 5.11.24
- simplified logic
- fixed bug where cancelling a file selection incorrectly deletes first doc

22995 Fixed bug

---

package-lock.json
package.json
src/components/ContinuationIn/ContinuationAuthorization.vue
src/components/common/FileUploadPreview.vue
src/mixins/document-mixin.ts
tests/unit/FileUploadPreview.spec.ts

*Issue #:* bcgov/entity#22995
- app version = 5.11.25
- added periods to error messages
- added busy spinner for feedback and to avoid extra clicks
- added extra check for valid file
- upated unit tests

22995 Added spinner + extra error handling

---

package-lock.json
package.json
src/store/store.ts
tests/unit/App.spec.ts

*Issue #:* /bcgov/entity#23554
- Fixed the Restoration Application page Fee Summary Bug, now showing $0 initially, until the user selects a restoration type

23554 - Fixed the Restoration Application Fee Summary Bug

---

package-lock.json
package.json
src/App.vue
src/components/Amalgamation/BusinessTypeHelp.vue
src/components/ContinuationIn/AuthorizationInformation.vue
src/components/ContinuationIn/AuthorizationProof.vue
src/components/ContinuationIn/ExtraproRegistration.vue
src/components/ContinuationIn/ManualBusinessInfo.vue
src/components/ContinuationIn/SummaryBusinessPreviousJurisdiction.vue
src/components/ContinuationIn/SummaryExtraprovincialRegistration.vue
src/components/ContinuationIn/UnlimitedLiabilityCorporationHelp.vue
src/components/ContinuationIn/UploadAffidavit.vue
src/components/common/NameRequestInfo.vue
src/interfaces/filing-interfaces/filing-interfaces.ts
src/interfaces/store-interfaces/state-interfaces/existing-business-info-interface.ts
src/mixins/filing-template-mixin.ts
src/store/store.ts
src/views/ContinuationIn/ContinuationInAuthorization.vue
src/views/ContinuationIn/ContinuationInBusinessBc.vue
src/views/ContinuationIn/ContinuationInReviewConfirm.vue
tests/unit/AuthorizationInformation.spec.ts
tests/unit/ContinuationInBusinessBc.spec.ts
tests/unit/ContinuationInReviewConfirm.spec.ts
tests/unit/ContinuationInUploadAffidavit.spec.ts
tests/unit/SummaryBusinessPreviousJurisdiction.spec.ts
tests/unit/SummaryExtraprovincialRegistration.spec.ts

*Issue #:* bcgov/entity#23514
**Note: there's still a work-around for testing [here](https://github.com/bcgov/business-create-ui/blob/01d87caebdfe4bd06746c157bfb966d2adfda9fb/src/App.vue#L953) that will need to be removed soon (but not yet).**
- app version = 5.12.3
- misc cleanup
- updated NameRequestInfo to support hiding NR number
- updated NameRequestInfo to support hiding applicant info
- created AuthorizationInformation component for step 1
- updated misc labels per designs
- updated validation properties and logic
- added checkmarks to summary pages
- created new summary section for AB ULC info (affidavit file)
- added validation and step link to summary page
- added ULC help component
- added help to UploadAffidavit
- added expro confirmation property and …

23514 More incremental development on continuation application

---

package-lock.json
package.json
src/resources/ContinuationIn/C.ts
src/resources/ContinuationIn/CBEN.ts
src/resources/ContinuationIn/CCC.ts
src/resources/ContinuationIn/CUL.ts

*Issue #:* bcgov/entity#23514
- app version = 5.12.4
- imported new shared Approval Type component (with lint fix)
- imported new shared Certify component (with pronoun and colour fix)
- updated entity display (per Jacqueline)

23514 Override input label and text + fix pronoun

---

package-lock.json
package.json
src/App.vue

*Issue #:* bcgov/entity#23514
- app version = 5.12.6
- removed cont in state work-around

23514 Remove testing workaround (status)

---

package-lock.json
package.json
src/components/ContinuationIn/AuthorizationProof.vue
src/components/ContinuationIn/UnlimitedLiabilityCorporationInformation.vue
tests/unit/UnlimitedLiabilityCorporationInformation.spec.ts

*Issue #:* bcgov/entity#23754
- app version = 5.12.11
- deleted "upload files will be renamed" statement per Jacqueline
- fixed some whitespace

23754 Deleted obsolete statement

---

package-lock.json
package.json
src/components/ContinuationIn/ExtraproRegistration.vue
src/interfaces/store-interfaces/state-interfaces/existing-business-info-interface.ts
src/mixins/filing-template-mixin.ts

*Issue #:* /bcgov/entity#24141
- Retain the founding date from Colin for the continuation filing

24141 - Added founding date not changed from Colin

---

package-lock.json
package.json
src/views/Incorporation/IncorporationReviewConfirm.vue

*Issue #:* /bcgov/entity#24082
- Add reset for CertifyState validity in case Incorporation Application fails when filed (same logic used in Amalgamation and Continuation In)
- Update patch version

24082 Fix Review and Certify Stepper Validation when Incorporation Fails

---

package-lock.json
package.json
src/views/Amalgamation/ReviewConfirm.vue
src/views/ContinuationIn/ContinuationInReviewConfirm.vue
src/views/Dissolution/DissolutionReviewConfirm.vue
src/views/Restoration/RestorationReviewConfirm.vue

*Issue #:* /bcgov/entity#23970
- Updated the Certify Legal Name editing condition on the Review/Confirm page to allow editing of the legal name for all users.
- The following filing types have been modified:
- Amalgamation
- Continuation In
- Dissolution
- Restoration (while general users cannot access this page, we ensure that the Certify Legal Name is editable in all filings for safety measures.)
**Note**:
According to Mihai's feedback, firms and coops types are not considered in this bug fix.
- The following filings remain unchanged:
- Dissolution Firm
- Registration
- IA
**Result**:
Before:
After:
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui …

23970 - Allow editable certify legal name

---

package-lock.json
package.json
src/App.vue

*Issue #:* /bcgov/entity#24104
- Hide the Fee Summary for Continuation Authorization

24104 - Hide Fee Summary for Continuation Authorization

---

src/components/ContinuationIn/AuthorizationInformation.vue
src/components/ContinuationIn/AuthorizationProof.vue
src/components/ContinuationIn/UnlimitedLiabilityCorporationInformation.vue
src/constants/constants.ts
src/enums/documentTypes.ts
src/enums/index.ts
src/interfaces/filing-interfaces/filing-interfaces.ts
src/interfaces/store-interfaces/state-interfaces/authorization-proof-interface.ts
src/interfaces/store-interfaces/state-interfaces/continuation-in-state-interface.ts
src/interfaces/store-interfaces/state-interfaces/existing-business-info-interface.ts
src/mixins/document-mixin.ts
src/mixins/filing-template-mixin.ts
src/store/state/state-model.ts
src/store/store.ts
src/utils/AxiosInstance.ts
src/utils/FetchConfig.ts

*Issue #:* /bcgov/entity#23446
- Updated `AuthorizationProof` component
- Updated `UnlimitedLiabilityCorporationInformation` component
- Upload document function to Document Record Service
- Delete document from Document Record Service
- Get/Set `consumerDocumentId`
- Added 3 new env variables

replaced Minio with Document Record Service

---

package-lock.json
package.json
src/components/Restoration/BusinessName.vue
src/components/common/EntityInfo.vue

*Issue #:* /bcgov/entity#26104
- The Bug is: When file a restoration, input a name request, the entity info doesn't show the NR name
- Fixed the bug for all company type restoration

26104 - Display NR name when restoration

---

.env.example
package-lock.json
package.json
src/services/business-lookup-services.ts
tests/unit/business-lookup-services.spec.ts

*Issue #:* bcgov/entity#26571
- app version = 5.14.16
- updated reg search URL in example env file
- used separate Axios instance in business lookup services, with own headers that don't include App-Name

26471 Exclude App-Name from reg search API calls

---

package-lock.json
package.json
src/components/common/ListShareClass.vue

*Issue #:* /bcgov/entity#26856
- Make the icons and text in the Share Class "more actions" drop down blue

26856 - Fix Styling for Share Class More Actions Drop Down Menu

---

package-lock.json
package.json
src/components/Amalgamation/BusinessTable.vue
src/components/Amalgamation/BusinessTableSummary.vue

*Issue #:* /bcgov/entity#28384 
- Since we don't have access to the `contacts` for unaffiliated businesses, we will display the text "Email not available":

28384 - Fix Empty Amalgamation Table for Drafts with Unaffiliated Businesses

---

package-lock.json
package.json
src/App.vue
src/components/common/OfficeAddresses.vue
src/interfaces/index.ts
src/interfaces/stepper-interfaces/DefineCompany/address-interfaces.ts
src/interfaces/store-interfaces/state-interfaces/account-information-interface.ts
src/mixins/common-mixin.ts
src/views/Restoration/RestorationBusinessInformation.vue
tests/unit/App.spec.ts
tests/unit/FileUploadPreview.spec.ts
tests/unit/RestorationBusinessInformation.spec.ts

*Issue #:* bcgov/entity#29124
- app version = 5.16.1
- load office addresses for restorations only
- used EmptyAddresses for some inits
- moved isEmptyAddress to common mixin
- set labels to bold
- added logic to show static vs editable addresses in restoration
- fixed/updated unit tests

29124 Fetch addresses and make non-editable for restoration filing

---

package-lock.json
package.json
src/mixins/filing-template-mixin.ts
src/views/Restoration/RestorationBusinessInformation.vue

*Issue #:* bcgov/entity#29124
- app version = 5.16.2
- only save records and registered office (not custodial office)
- updated logic so addresses are non-editable only for limited restoration

29124 allow editing for full resto + remove undesired custodial address
