src/main.ts
* Commented out authentication calls for ease of initial set up. 
=> Disabled Auth

.github/workflows/build-master.yml, .github/workflows/pr.yml, Dockerfile
Signed-off-by: thor wolpert <thor@wolpert.ca>
*Issue #:* /bcgov/entity#1893
- Dockerfile to build the app and serve from a Caddy container
- GHAction for PR, unit tests, lint and build image:pr#
- GHAction for build off master once PR is merged
=> initial GHActions setup for build, using an alternative Registry for now.

package-lock.json
Signed-off-by: thor wolpert <thor@wolpert.ca>
*Issue #:* /bcgov/entity#1893
adding package-lock, as it is required in the GHA
=> GHA CI requires package-lock.json, so adding this.

package.json, public/index.html, src/assets/styles/base.scss
*Issue #:* none
- updated app name
- updated app title
- updated h2 font-size (same as coops-ui)
=> updated app name and title

.dockerignore, .env.production, Dockerfile, k8s/templates/bcrs-entities-create-dc.json, nginx.conf
Signed-off-by: thor wolpert <thor@wolpert.ca>
*Issue #:* /bcgov/entity#1893
- Dockerfile updated for multi-stage build and nginx
- k8s deployment updated
=> completed files for build/deploy from GH Actions

src/components/common/EntityInfo.vue, tests/unit/entityInfo.spec.ts
*Issue #:* /bcgov/entity#1885
* Implemented functionality ( For demo and MVP purposes ) to the entity info header based off of the users entity type selection.
* Updated unit testing.
=> #1885 Header Functionality

src/App.vue, src/views/DefineCompany.vue, src/views/ReviewConfirm.vue
- fixed affix
- scoped the component style sections
- deleted obsolete code
=> fixed affix

src/App.vue, src/components/ReviewConfirm/Summary.vue, src/views/DefineCompany.vue, src/views/ReviewConfirm.vue, tsconfig.json
- fixed padding/margins on review page
- also made Registered Office Info dependent on having an entity type
- also fixed strict flags dependency
=> fixed padding/margins on review page

src/components/common/Actions.vue, src/mixins/legal-api-mixin.ts, tests/unit/Actions.spec.ts
*Issue #:* /bcgov/entity#1896
This code is an update to the frontend regarding some new information about the endpoints.
Essentially the need for a `draft` parameter is no longer required, also the complete filing will be a 2 step request to ensure there is a `filingId` even if the user goes through the flow in one shot without saving. 
* Implemented Unit testing
* updated competeFilings functionality
=> Save& File - Unit testing & completeFiling Functionality

.gitignore, package-lock.json, package.json, src/App.vue, src/assets/styles/base.scss, src/components/ReviewConfirm/Certify.vue, src/components/common/Stepper.vue, src/views/DefineCompany.vue
*Issue #:* /bcgov/entity#1892
- updated prototype stepper to use objects
- updated prototype stepper with correct icons
- updated prototype stepper with 'valid' checkmark
- set filing data according to entity type
- changed some v-if to v-show
- updated version to 0.2.0
- ignored template param files
=> improved prototype stepper

k8s/templates/bcrs-entities-create-dc.json
*Issue #:* /bcgov/entity#2391
- this is the Create DC file, updated with 2 new config map params
- this file requires a param file that contains the necessary config map parameters, but the param file is not checked in so I will email it separately
=> updated Create DC file (requires updated Param file - not checked in)

package.json, src/components/DefineCompany/OfficeAddresses.vue, src/views/DefineCompany.vue, tests/unit/DefineCompany.spec.ts, tests/unit/OfficeAddresses.spec.ts
*Issue #:* /bcgov/entity#2469
* Implemented unit testing for Office Addresses Components.
* Added some ID attributes for testing purposes.
=> #2469 BC-Create Office Addresses unit testing

.sonarcloud.properties
I copied this file from lear repo and then updated it.
=> Created .sonarcloud.properties file

package-lock.json, package.json, public/config/configuration.json, src/common/FeatureFlags.ts, src/main.ts, src/utils/config-helper.ts
*Description of changes:* Launch darkly integration for create business UI
=> Launch Darkly Integration for create business UI

src/App.vue, src/components/common/Stepper.vue
=> added line between steps in prototype stepper

src/App.vue, src/assets/styles/layout.scss, src/components/common/Stepper.vue
=> updated app max-width (per Jeremy, ie, same as auth-web)

src/common/FeatureFlags.ts, src/components/AddPeopleAndRoles/AddEditPerson.vue, src/components/AddPeopleAndRoles/ListPeopleAndRoles.vue, src/components/AddPeopleAndRoles/OrgPerson.vue, src/components/AddPeopleAndRoles/PeopleAndRoles.vue, src/components/AddPeopleAndRoles/index.ts, src/components/common/Stepper.vue, src/interfaces/index.ts, src/interfaces/stepper-interfaces/AddPeopleAndRole/add-people-role-interface.ts, src/interfaces/stepper-interfaces/AddPeopleAndRole/org-person-interface.ts, src/interfaces/stepper-interfaces/DefineCompany/address-interface.ts, src/interfaces/store-interfaces/state-interface.ts, src/interfaces/utils-interfaces/form-interface.ts, src/router/routes.ts, src/schemas/office-address-schema.ts, src/store/actions/actions-model.ts, src/store/getters/state-getters.ts, src/store/index.ts, src/store/mutations/mutations-model.ts, src/store/state/state-model.ts, src/views/AddPeopleAndRoles.vue
*Issue #:* /bcgov/entity#2716
* Initial commit for #2716. 
* Contains all work done by Lekshmi previously for adding the framework and Adding people/corps.
* Contains display list for persons incorporators with dummy functionality. 
=> #2716 display step 2

src/components/AddPeopleAndRoles/ListPeopleAndRoles.vue, src/components/AddPeopleAndRoles/OrgPerson.vue, src/components/AddPeopleAndRoles/PeopleAndRoles.vue, src/interfaces/stepper-interfaces/AddPeopleAndRole/org-person-interface.ts
Edit Person + Some business rules + Some validation logic + some fixes in the current code such as disabling the list when add or edit is in progress etc
=> Step 2 - Add/Edit Person + minor fixes

src/components/AddPeopleAndRoles/ListPeopleAndRoles.vue, src/components/AddPeopleAndRoles/PeopleAndRoles.vue
=> Issue fixes

src/components/AddPeopleAndRoles/PeopleAndRoles.vue, tests/unit/PeopleAndRoles.spec.ts
=> Added selectors + Unit tests for People and Roles parent page

tests/unit/OrgPerson.spec.ts
=> Adding flush promise to failed test

src/components/AddPeopleAndRoles/ListPeopleAndRoles.vue, src/components/AddPeopleAndRoles/OrgPerson.vue, src/components/AddPeopleAndRoles/PeopleAndRoles.vue
=> Incoporations step 2 PR UPDATES

src/components/AddPeopleAndRoles/ListPeopleAndRoles.vue, src/components/AddPeopleAndRoles/OrgPerson.vue, src/components/AddPeopleAndRoles/PeopleAndRoles.vue
*Issue #:* /bcgov/entity#2704, /bcgov/entity#2670, /bcgov/entity#2674, /bcgov/entity#2698, /bcgov/entity#2687
*Description of changes:* 
Implementation of Step 2 Add People and Roles + Step 5 summary of people and roles
PR Updates for the above!
=> Step 2 and Step 5 PR UPDATES

k8s/templates/bcrs-entities-create-dc.json, public/config/configuration.json, src/utils/auth-helpers.ts, src/utils/config-helper.ts
*Issue #:* /bcgov/entity#2960
- Updated configurtion.json to rename AUTH_API_URL to VUE_APP_AUTH_ROOT_API
- Updated k8s/templates to reflect changes
- Updated config-helper to reflect changes
- Updated release / deployment checklist to account for changes
=> ENTITY-2960 - Refactor Environment Property Keys

src/components/CreateShareStructure/ListShareClass.vue, src/components/CreateShareStructure/ShareClass.vue, src/components/CreateShareStructure/index.ts, src/interfaces/index.ts, src/interfaces/stepper-interfaces/CreateShareStructure/create-share-structure-interface.ts, src/interfaces/store-interfaces/state-interface.ts, src/router/routes.ts, src/store/actions/actions-model.ts, src/store/getters/state-getters.ts, src/store/index.ts, src/store/mutations/mutations-model.ts, src/store/state/state-model.ts, src/views/CreateShareStructure.vue
*Issue #:* /bcgov/entity#3027
*Description of changes:* 
Step 3 data structure and framework updates. 
- From what I understand, share class and share series has the same set of attributes. Share class c 
an have an array of share series as child elements based on an attribute value.
Step 3 is enabled now  so that everyone can check the flow. We can leave it as enabled or make it disabled till step 3 is fully ready.
=> Step 3 framework

public/config/configuration.json, src/App.vue, src/assets/styles/theme.scss, src/components/AddPeopleAndRoles/ListPeopleAndRoles.vue, src/components/AddPeopleAndRoles/OrgPerson.vue, src/components/AddPeopleAndRoles/PeopleAndRoles.vue, src/components/DefineCompany/OfficeAddresses.vue, src/components/Summary/SummaryDefineCompany.vue, src/components/common/Stepper.vue, src/interfaces/filing-interfaces/filing-interface.ts, src/interfaces/stepper-interfaces/AddPeopleAndRole/org-person-interface.ts, src/mixins/filing-template-mixin.ts, src/mixins/legal-api-mixin.ts, src/mixins/namex-api-mixin.ts, src/views/DefineCompany.vue, tests/unit/Actions.spec.ts, tests/unit/ListPeopleAndRoles.spec.ts, tests/unit/OrgPerson.spec.ts, tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#2762
* Includes data from step 2 into our filing body.
* Includes parsing data for step 2 from draft filings.
* Adjusts some legal api methods to adapt to some back end changes to the endpoints.
* Updates the unit tests to include the updated data set.
* Adjusts some string manipulation with the Namex NR Number handling.
* Removes hardcoded NR data from App.
* Assigns the EntityType as BCOMP until a time when Namex provides a Type. 
=> #2762 Step2 Drafts/Filing + NR Integration Updates.

package-lock.json, package.json
*Issue #:* /bcgov/entity#3043
- updated to latest common components to pick up config key name change
=> updated to latest common components to pick up config key name change

src/components/common/Stepper.vue
- changed the stepper text to a button so it's clickable to change step (route)
=> changed stepper text to a button

src/App.vue, src/main.ts, src/mixins/date-mixin.ts, src/mixins/name-request-mixin.ts, tests/unit/App.spec.ts
*Issue #:* /bcgov/entity#3164
- added token refresh service
- ~~added temporary date override (tomorrow) for currently-expired test NRs~~ removed
- fixed lint error
- added startup messages
=> added token refresh service

package-lock.json, package.json, src/App.vue, src/interfaces/filing-interfaces/filing-interface.ts, src/mixins/filing-template-mixin.ts, src/store/index.ts, tests/unit/App.spec.ts
*Issue #:* /bcgov/entity#2465
- Fix issue where parsing a draft will overwrite the name request state
- updated existing app component test and added a test for testing the NR store
=> 2465 nr state fix

src/components/CreateShareStructure/ListShareClass.vue
=> removed v-if for datatable

src/components/CreateShareStructure/ListShareClass.vue
* Fixed a dropdown bug i created.
=> Step3 dev updates

src/components/CreateShareStructure/ListShareClass.vue
* Fixed tag where no maximum is present.
* disabled series when the class doesn't have special rights.
=> Fixed no Maximum tag

src/components/CreateShareStructure/ShareStructure.vue, src/views/CreateShareStructure.vue
=> Validation rules for unique name and max share quantity of series

src/views/CreateShareStructure.vue
* Implemented Share Structure Help section
=> Step3 help tips

src/main.ts, src/router/index.ts, src/store/index.ts, tests/unit/Actions.spec.ts, tests/unit/App.spec.ts, tests/unit/DefineCompany.spec.ts, tests/unit/ListPeopleAndRoles.spec.ts, tests/unit/OfficeAddresses.spec.ts, tests/unit/OrgPerson.spec.ts, tests/unit/PeopleAndRoles.spec.ts, tests/unit/ReviewConfirm.spec.ts, tests/unit/Stepper.spec.ts, tests/unit/entityInfo.spec.ts, tests/unit/nameRequestInfo.spec.ts
*Issue #:* /bcgov/entity#3359
- updated to load router AFTER loading config
- updated store similarly
- (now same architecture as Filings UI)
=> fixed Create UI not redirecting to signin the first time

src/components/CreateShareStructure/ListShareClass.vue
* Fixed my string template issue on the par value.
=> Fixed String Template

src/components/CreateShareStructure/ShareStructure.vue, src/views/CreateShareStructure.vue, tests/unit/ListShareClass.spec.ts, tests/unit/ShareStructure.spec.ts
*Issue #:* /bcgov/entity#3032
Added missing validations
Added unit tests
=> Additional validations + Unit tests

package-lock.json, package.json
*Issue #:* /bcgov/entity#3338
- explicitly added Babel package to prod dependencies (it was previously only a dev dependency of other packages)
Ref: https://stackoverflow.com/questions/61238650/i-am-having-an-issue-with-babel-building-angular-app-for-production
=> added Babel package to try to fix CI build error

Jenkinsfiles/deploy-dev.groovy, Jenkinsfiles/deploy-prod.groovy, Jenkinsfiles/deploy-test.groovy
Signed-off-by: Kial Jinnah <kialj876@gmail.com>
*Issue #:* /bcgov/entity#
- made an error in how it gets the deployment
- tested new fix already and it works
=> fixed pipelines

src/components/CreateShareStructure/ListShareClass.vue, tests/unit/ListShareClass.spec.ts
* Added an additional unit testing for verifying the props data after using the sort functionality.
=> Additional test for sorting

src/interfaces/filing-interfaces/filing-interface.ts, src/mixins/filing-template-mixin.ts, tests/unit/Actions.spec.ts, tests/unit/App.spec.ts
*Issue #:* /bcgov/entity#3036
* Implemented share classes data into Filing.
* Added the share classes into the parse draft method.
* Updated unit testing, got them up to date with the current data structure. 
=> ShareClasses Filing / Parsing Drafts

k8s/README.md
Signed-off-by: Kial Jinnah <kialj876@gmail.com>
- added note to not push param values into GitHub
=> updated readMe

.eslintrc.js, src/components/DefineCompany/BusinessContactInfo.vue
*Issue #:* /bcgov/entity#2556
- update email validation to match auth profile page
=> 2556 - update email validation

package-lock.json, package.json
*Issue #:* N/A
- updated sbc-common-components to 2.1.27
=> updated sbc-common-components to 2.1.27

src/components/ReviewConfirm/IncorporationDateTime.vue, src/components/common/Actions.vue, src/mixins/date-mixin.ts, tests/unit/IncorporationDateTime.spec.ts
*Issue #:* /bcgov/entity#3525
* Implemented UI indicators for the various invalid states of Dates and Times.
* Refactored some Date functionality into the DateMixin.
* Applied DateTime Validations at File&Pay.
* Applied DateTime Validations when returning from a draft.
* Fixed unit tests affected by refactors.
* Added new unit testing.
=> #3525 UI - Future Effective Validations

src/components/common/Actions.vue
*Issue #:* /bcgov/entity#3644
* Fixes bug to allow for immediate filings without validating the Date
=> #3644 - Immediate Filing Validation Bug FIx

src/views/ReviewConfirm.vue
*Mockup:* https://preview.uxpin.com/d7266b8b6fb8bd80acc0ff38ff5c946434492f5e#/pages/122406228
* Tiny Update to font weight on subtext in Incorporation DateTime description.
=> Date time subtext update

src/components/ReviewConfirm/IncorporationDateTime.vue
*Issue #:* /bcgov/entity#3706
* Updated Date picker to horizontal orientation.
=> #3706 date selector update

package-lock.json, package.json, src/App.vue, src/components/DefineCompany/FolioNumber.vue, src/components/DefineCompany/index.ts, src/components/Summary/SummaryDefineCompany.vue, src/enums/accountTypes.ts, src/enums/index.ts, src/interfaces/filing-interfaces/filing-interface.ts, src/interfaces/index.ts, src/interfaces/stepper-interfaces/DefineCompany/define-company-interface.ts, src/interfaces/store-interfaces/state-interface.ts, src/interfaces/store-interfaces/state-interfaces/account-information-interface.ts, src/interfaces/store-interfaces/state-interfaces/name-request-interface.ts, src/mixins/filing-template-mixin.ts, src/store/actions/actions-model.ts, src/store/getters/state-getters.ts, src/store/index.ts, src/store/mutations/mutations-model.ts, src/store/state/state-model.ts, src/views/DefineCompany.vue, tests/unit/DefineCompany.spec.ts, tests/unit/FolioNumber.spec.ts
*Issue #:* /bcgov/entity#3764
- add folio number to step 1
- updated state model
- updated filing template mixin
=> 3764-folio-number

package.json, public/config/configuration.json, src/App.vue, src/components/common/Actions.vue, src/components/common/EntityInfo.vue, src/components/common/NameRequestInfo.vue, src/interfaces/filing-interfaces/filing-interface.ts, src/interfaces/store-interfaces/state-interface.ts, src/mixins/entityFilter-mixin.ts, src/mixins/filing-template-mixin.ts, src/mixins/legal-api-mixin.ts, src/mixins/name-request-mixin.ts, src/router/index.ts, src/store/actions/actions-model.ts, src/store/getters/state-getters.ts, src/store/index.ts, src/store/mutations/mutations-model.ts, src/store/state/state-model.ts, tests/unit/Actions.spec.ts, tests/unit/App.spec.ts, tests/unit/DefineCompany.spec.ts, tests/unit/OfficeAddresses.spec.ts, tests/unit/nameRequestInfo.spec.ts
*Issue #:* /bcgov/entity#3489
Changed the Incorporation Application to use temporary registration Id, still need to refactor NameRequest reliant components (tickets created for this)
=> 3489 add numbered ia

package-lock.json, package.json, src/App.vue, src/components/ReviewConfirm/IncorporationDateTime.vue
*Issue #:* /bcgov/entity#3863
* Refactored the Min and Max Date for allowed for the Date selector to reflect Local Time not UTC time in the selector. 
=> Fixed Date Selector to reflect local time

src/components/Summary/SummaryDefineCompany.vue, src/components/common/EntityInfo.vue, src/components/common/NameRequestInfo.vue, src/components/dialogs/NameRequestInvalidErrorDialog.vue, src/mixins/filing-template-mixin.ts, src/store/getters/state-getters.ts, tests/unit/NameRequestInvalidErrorDialog.spec.ts, tests/unit/entityInfo.spec.ts, tests/unit/nameRequestInfo.spec.ts
*Issue #:* /bcgov/entity#2548
* Updated the following components to handle Numbered Companies and NR's
* UXPin Link: https://preview.uxpin.com/30c9580e6c2ac2c8ce80645c7688b23555f1a977#/pages/129166305/simulate/no-panels
* Updated Entity Info Header
* Updated Step 1 Business Info Component
* Updated Updated DefineCompany Summary
* Updated nameRequestInvalid Dialog
*Additional Fix out of ticket scope but snuck it in for efficiency, please slap my hand and ask for another PR if required ;)*
*UX fix to handle the default effectiveDate being set upon draft creation/saves.
=> #2548 Numbered Company UI Info

src/interfaces/filing-interfaces/filing-interface.ts, src/mixins/filing-template-mixin.ts
*Issue #:* /bcgov/entity#3926
* Added boolean to header which will give the backend a way of knowing if a filing in history was future effective.
=> Add isFutureEffective Boolean to Header

src/App.vue, src/components/common/Actions.vue, src/components/dialogs/BcolErrorDialog.vue, src/components/dialogs/index.ts, src/mixins/bcol-mixin.ts, src/mixins/index.ts, tests/unit/BcolErrorDialog.spec.ts
*Issue #:* /bcgov/entity#2764
Incorporation side of 2764
=> add error dialog for BCOL failures

src/components/common/EntityInfo.vue, tests/unit/entityInfo.spec.ts
*Issue #:* /bcgov/entity#3927
* Implemented Breadcrumb for Create UI
* Updated EntityInfo Tests
*NOTES:*
* Navigation is rather limited in this UI resulting in a rather static breadcrumb with a few computed values.
* Adding the individual steps to the breadcrumb seemed too granular. Feel free to comment if you think it should be otherwise.
* If we determine we wanted something more dynamic based on the routes, we can add the breadcrumb meta data to the individual step routes. 
=> #3927 Breadcrumb for Create UI

package-lock.json, package.json
*Issue #:* /bcgov/entity#4044
* Updated UI Version to .5.
* Updated Common Components Dependency in Create UI.
=> Updated Common Components Dependency

src/resources/benefitCompanyStatementResource.ts, src/resources/index.ts, src/views/DefineCompany.vue, src/views/ReviewConfirm.vue, tests/unit/DefineCompany.spec.ts, tests/unit/ReviewConfirm.spec.ts
*Issue #:* /bcgov/entity#4000, /bcgov/entity#3721
- add benefit company statement to define company and review steps
- annual reminder text update
=> 4000/3721 - benefit company statement / annual reminder text

src/App.vue, src/components/dialogs/AccountAuthorizationDialog.vue, src/components/dialogs/InvalidIncorporationApplicationDialog.vue, src/components/dialogs/index.ts, src/enums/filingStatus.ts, src/enums/index.ts, tests/unit/AccountAuthorizationDialog.spec.ts, tests/unit/App.spec.ts, tests/unit/InvalidIncorporationApplicationDialog.spec.ts
*Issue #:* /bcgov/entity#4027
- added logic on app start up to show invalid IA dialog if the filing is not in an editable state (Draft)
- added filing status enum
- updated authorization dialog text
- added in invalid ia dialog unit tests
- added authorization dialog unit tests (I didn't see existing ones)
=> 4027 - filed IA handling

src/components/common/Actions.vue
*Issue #:* /bcgov/entity#4046
- Moved the setter for isFilingPaying so it is cleared on error so the file and pay button keeps the loading indicator and actions disabled until redirects happen.
=> 4046 - file and pay updates

package-lock.json, package.json
* Rolling Back SBC Common Component Dependency until POST Tuesdays Release.
=> Rolled Back SBC

src/App.vue, src/components/common/Actions.vue, src/components/dialogs/FileAndPayInvalidNameRequestDialog.vue, src/components/dialogs/index.ts, tests/unit/Actions.spec.ts, tests/unit/FileAndPayInvalidNameRequestDialog.spec.ts, tests/unit/ShareStructure.spec.ts
*Issue #:* /bcgov/entity#4037
Added an error dialog
Modified file and pay method to validate NR for a named company
Added tests
=> NR validation before file and pay

src/components/CreateShareStructure/ShareStructure.vue, tests/unit/ShareStructure.spec.ts
*Issue #:* /bcgov/entity#4100
Updated the par value rule regex
Added a new test
=> Bug fix - share structure par value

src/components/common/Stepper.vue, tests/unit/Stepper.spec.ts
*Issue #:* /bcgov/entity#
* Enabled stepper activation on wrapper element
* Added hover and current step selected styling
* Added tabbing through steps for accessibility. 
=> Stepper update

src/App.vue, src/mixins/bcol-mixin.ts
*Issue #:* /bcgov/entity#3685
*Issue #:* /bcgov/entity#4093
=> fix 3685 and 4093  - business create

src/App.vue
*Issue #:* /bcgov/entity#4052
- moved code that populates ID before code that uses it
=> fixed Exit action not navigating to Filings UI with id

package-lock.json, package.json
*Issue #:* /bcgov/entity#4192
- updated version to 1.1.0
=> updated version to 1.1.0

src/components/DefineCompany/AddNameTranslation.vue, src/components/DefineCompany/ListNameTranslations.vue, src/components/DefineCompany/index.ts, src/components/Summary/SummaryDefineCompany.vue, src/components/common/NameRequestInfo.vue, src/interfaces/filing-interfaces/filing-interface.ts, src/interfaces/store-interfaces/state-interface.ts, src/mixins/filing-template-mixin.ts, src/store/actions/actions-model.ts, src/store/getters/state-getters.ts, src/store/index.ts, src/store/mutations/mutations-model.ts, src/store/state/state-model.ts, src/views/DefineCompany.vue, tests/unit/Actions.spec.ts, tests/unit/AddNameTranslation.spec.ts, tests/unit/ListNameTranslations.spec.ts, tests/unit/nameRequestInfo.spec.ts
*Issue #:* /bcgov/entity#2464
* Implements UI for the handling of Optional Name Translations.
* Adds 2 new sub components - Adding/editing Name Translations & Functional List of Name Translations.
* Added to Name Translations to the summary page, filings and parsing from drafts.
* Implemented Unit tests.
=> #2464 UI Name Translations

package-lock.json, package.json, src/App.vue
=> updated sbc-common-components dependency to 2.2.9

package-lock.json, package.json
*Issue #:* /bcgov/entity#4550
* Upgraded SBC Common Components dependency
=> Upgrade SBC Version

src/views/auth/Signin.vue
- updated signin complete event from sbc-common-component
=> updated signin complete event from sbc-common-component

src/interfaces/filing-interfaces/filing-interface.ts, src/mixins/filing-template-mixin.ts, tests/unit/Actions.spec.ts
=> Name translations update

src/utils/axios-auth.ts
*Issue #:* /bcgov/entity#3933
- sends entry messages on errors for api requests
=> #3933 sends entry messages on errors for api requests

package-lock.json, package.json, src/App.vue, vue.config.js
**Not ready to merge -- need sbc-common-components 2.3.3 (still in PR).**
*Issue #:* /bcgov/entity#2555
- added app friendly name
- injected env variables for app name and version
- pass app name-version string to Sbc Footer (requires next sbc-common-components version)
- also updated misc dependencies
*Screenshots:*
The information icon:
The tooltip (when hovering over the icon):
=> added app info to footer

src/interfaces/filing-interfaces/filing-interface.ts, src/mixins/filing-template-mixin.ts, tests/unit/Actions.spec.ts, tests/unit/App.spec.ts
*Issue #:* /bcgov/entity#4668
Updates to use the new share structure
=> Share structure changes for create UI

src/components/IncorporationAgreement/AgreementType.vue
*Issue #:* None.
I noticed this was corrupted so I fixed it.
=> fixed agreement summary title

src/enums/entityTypes.ts, src/resources/certifyStatementResource.ts, tests/unit/Actions.spec.ts, tests/unit/AgreementType.spec.ts, tests/unit/App.spec.ts, tests/unit/DefineCompany.spec.ts, tests/unit/FileAndPayInvalidNameRequestDialog.spec.ts, tests/unit/OfficeAddresses.spec.ts, tests/unit/OrgPerson.spec.ts, tests/unit/ReviewConfirm.spec.ts, tests/unit/ShareStructure.spec.ts, tests/unit/entityInfo.spec.ts, tests/unit/nameRequestInfo.spec.ts
*Issue #:* /bcgov/entity#5048
- Enum BC to BEN
- Test fixes
=> 5048: Legal Type for Benefit Company from BC to BEN

package-lock.json, package.json
*Issue #:* /bcgov/entity#4875
* Updated App version
* Updated SBC dependency version
=> Updated SBC Version and App Version

package-lock.json, package.json, src/components/AddPeopleAndRoles/OrgPerson.vue, src/components/AddPeopleAndRoles/PeopleAndRoles.vue, tests/unit/OrgPerson.spec.ts
*Issue #:* /bcgov/entity#5312
(This is a port of the changes I made in Edit UI.)
- changed roles to a "group"
- added validation rules for roles
- always enable add/edit Person/Org Done button
- validate form when Done is clicked
- updated Cancel button style (same as Correction design)
- added transparent role icon for proper spacing
- updated/added unit tests
- misc cleanup
- updated version to 1.3.1
=> implemented role rules/validation

src/components/CreateShareStructure/ShareStructure.vue, src/interfaces/stepper-interfaces/CreateShareStructure/create-share-structure-interface.ts, src/views/CreateShareStructure.vue, tests/unit/ShareStructure.spec.ts
*Issue #:* /bcgov/entity#5398
* Updated the Share Structure ID to be a UUID string.
* Updated Unit testing.
=> Share Structure ID Refactor

.github/workflows/cd.yml
*Issue #:* /bcgov/entity#5626
Update for deprecating set-env command of GHA.
=> Update for set environment variables issue of GHA.

src/App.vue
Issue #: /bcgov/entity#5802
This was causing "Leave site? Changes you made may not be saved." after trying to file-and-save and return to dashboard, even though all changes were saved.
=> fixed setter

src/components/AddPeopleAndRoles/PeopleAndRoles.vue, src/components/DefineCompany/BusinessContactInfo.vue, src/views/ReviewConfirm.vue
*Issue #:* /bcgov/entity#4624
- fixed typo in People and Roles text
- fixed typo in Business Contact Info title
- fixed typo in Review Confirm text
=> fixed typos

.github/workflows/cd.yml, .sonarcloud.properties, CONTRIBUTING.md, README.md, codecov.yaml, k8s/templates/bc.yaml, k8s/templates/pipeline.yaml, package-lock.json, package.json
*Issue 3389:* https://github.com/bcgov/entity/issues/3389
1. Rename the repo to 'business-create-ui';
2. Switch the default branch to 'main';
3. Update the Github actions scripts;
4. Update the Jenkins pipeline templates;
5. Update Sonar config;
6. Update Readme;
=> Rename repo and switch the default branch to 'main'.

package-lock.json, package.json
- updated vue-test-utils-helpers import
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the business-filings-ui license (Apache 2.0).
=> Updated vue-test-utils-helpers import

.github/workflows/cd.yml, Dockerfile, Makefile, devops/vaults.json
1. Migrated the environments to 1password;
2. Modify CD flow on makefile;
3. Modify CI/CD GHA scripts;
=> Update CICD flow.

nginx.conf, package-lock.json, package.json
*Issue #:* /bcgov/entity#7263
- added nginx config to disable index.html caching
- updated sbc-common-components dependency
=> Updated sbc-common-components dependency + updated caching config

package-lock.json, package.json
*Issue #:* /bcgov/entity#7373
* Update app version number to 1.5.7
* Update to use latest sbc-common-components dependency
=> 7373 Update to latest sbc-common-components

package-lock.json, package.json, src/components/CreateShareStructure/ShareStructure.vue, tests/unit/ShareStructure.spec.ts
*Issue #:* /bcgov/entity#7505
- added rule for required number of shares
- added rule for number of shares > 0
- added unit tests
=> Added validation for number of shares = 0

package-lock.json, package.json, src/components/CreateShareStructure/ShareStructure.vue, tests/unit/ShareStructure.spec.ts
*Issue #:* /bcgov/entity#7488
- added shares max digits rule (as per db schema)
=> Prevent too large a number of shares

package-lock.json, package.json
*Issue #:* bcgov/entity#6682
Fix bug and disable browser autocomplete when entering address
=> Update sbc-common-component version in package.json

package-lock.json, package.json, public/config/configuration.json, src/utils/config-helper.ts
*Issue #:* /bcgov/entity#7694
- updated Auth Api Config workaround
- updated local configuration
=> Updated auth config key loading

package-lock.json, package.json
*Issue #:* /bcgov/entity#6682
Update sbc-common-components version number
=> Update sbc-common-components version number

package-lock.json, package.json, src/App.vue
*Issue #:* /bcgov/entity#7764
- Added PaySystemAlert to business-create-ui
=> 7764 - Added PaySystemAlert to business-create-ui

package-lock.json, package.json, src/resources/limitedCompany.ts, src/resources/unlimitedCompany.ts, src/views/IncorporationAgreement.vue, tests/unit/AgreementType.spec.ts
*Issue #:* /bcgov/entity#6858
* added link to section 42
* updated verbiage for limited and unlimited companies
=> Incorp Agreement Ux Updates

package-lock.json, package.json, src/App.vue, src/components/AddPeopleAndRoles/PeopleAndRoles.vue, src/resources/benefitCompany.ts, src/resources/communityContributionCompany.ts, src/resources/cooperative.ts, src/resources/limitedCompany.ts, src/resources/unlimitedCompany.ts, src/views/DefineCompany.vue, tests/unit/DefineCompany.spec.ts
*Issue #:* /bcgov/entity#6856
* Updated verbiage.
* Removed blank LTD statement.
* Added People and roles btn text for all entities. 
=> Incorporation Application UX Updates

src/components/AddPeopleAndRoles/OrgPerson.vue
*Issue #:* /bcgov/entity#6856
* Updated incorporator label to make COOP the exception.
=> Updated incorporator label

package-lock.json, package.json, src/assets/styles/base.scss, src/assets/styles/overrides.scss, src/components/ReviewConfirm/DocumentDelivery.vue, src/components/ReviewConfirm/index.ts, src/resources/cooperative.ts, src/store/getters/state-getters.ts, src/views/ReviewConfirm.vue, tests/unit/DocumentDelivery.spec.ts
*Issue #:* /bcgov/entity#8366
* Some Review view layout updates.
* Relocated Document delivery documents to its own section.
=> Implemented Document Delivery

package-lock.json, package.json, src/App.vue, src/components/ReviewConfirm/IncorporationDateTime.vue, src/components/Summary/SummaryDefineCompany.vue, src/components/common/Actions.vue, src/mixins/date-mixin.ts, src/mixins/filing-template-mixin.ts, src/mixins/name-request-mixin.ts, src/views/ReviewConfirm.vue, tests/unit/Actions.spec.ts, tests/unit/App.spec.ts, tests/unit/ReviewConfirm.spec.ts
*Issue #:* /bcgov/entity#8352
- throw error if nameRequest object not in filing
- display errors on unexpected errors
- display useful logs if NR checks fail
- ensure NR type matches entity type
- map NR type to entity type
- added NR validation checks
- fixes for date TODOs
- added date mixin methods
- added code exceptions for Jest
- app version: 2.0.6
=> 8352 implemented misc TODOs

src/assets/styles/theme.scss, src/components/AddPeopleAndRoles/ListPeopleAndRoles.vue, src/components/AddPeopleAndRoles/PeopleAndRoles.vue, src/components/CreateMemorandum/UploadMemorandum.vue, src/components/CreateRules/UploadRules.vue, src/components/CreateShareStructure/ListShareClass.vue, src/components/DefineCompany/BusinessContactInfo.vue, src/components/DefineCompany/OfficeAddresses.vue, src/components/IncorporationAgreement/AgreementType.vue, src/components/ReviewConfirm/IncorporationDateTime.vue, src/components/Summary/SummaryDefineCompany.vue, src/components/common/Actions.vue, src/components/common/Stepper.vue, src/views/DefineCompany.vue, tests/unit/AgreementType.spec.ts, tests/unit/ListPeopleAndRoles.spec.ts
=> 8367 update UI validation

package-lock.json, package.json, src/interfaces/resource-interfaces/resource-interface.ts, src/resources/benefitCompany.ts, src/resources/communityContributionCompany.ts, src/resources/cooperative.ts, src/resources/limitedCompany.ts, src/resources/unlimitedCompany.ts, src/store/state/resource-model.ts, src/views/IncorporationAgreement.vue, src/views/ReviewConfirm.vue, tests/unit/AgreementType.spec.ts, tests/unit/DefineCompany.spec.ts
*Issue #:* /bcgov/entity#8366
- added resource property for entity display string
- removed extra colon from resource title
- replaced ’ with '
- replaced some ` with '
- fixed line indents
- fixed coop section and act
- app version: 2.0.7
=> 8366 Misc fixes to certify section for coops

package-lock.json, package.json, src/App.vue, src/assets/styles/overrides.scss, src/components/DefineCompany/BusinessContactInfo.vue, src/components/DefineCompany/CooperativeType.vue, src/components/DefineCompany/index.ts, src/components/Summary/SummaryDefineCompany.vue, src/components/common/EntityInfo.vue, src/components/common/Stepper.vue, src/enums/coopType.ts, src/enums/index.ts, src/interfaces/filing-interfaces/filing-interface.ts, src/interfaces/stepper-interfaces/DefineCompany/define-company-interface.ts, src/interfaces/store-interfaces/state-interfaces/tombstone-interface.ts, src/mixins/filing-template-mixin.ts, src/store/actions/actions-model.ts, src/store/getters/state-getters.ts, src/store/mutations/mutations-model.ts, src/store/state/state-model.ts, src/views/DefineCompany.vue, tests/unit/App.spec.ts, tests/unit/CooperativeType.spec.ts, tests/unit/entityInfo.spec.ts
*Issue #:* /bcgov/entity#8514
* Added Cooperative Association component and review summary version.
* Updated and added validations for new component.
* Include cooperative type into filing template and draft parsing.
* Updated Entity Info Header to meet new UX and Design requirements.
* Some verbiage updates to Office Addresses.
* Stepper Bottom border style update.
=> Coop Association type and UX Updates

src/mixins/filing-template-mixin.ts
*Issue #:* /bcgov/entity#8514
* Fixed type error of improper value assignment.
=> Fixed filing template

package-lock.json, package.json, src/components/DefineCompany/CooperativeType.vue, src/enums/coopType.ts
*Issue #:* /bcgov/entity#8514
* Updated type names to match requirements update.
=> Updated Type Names

package-lock.json, package.json, src/assets/styles/overrides.scss, src/components/AddPeopleAndRoles/ListPeopleAndRoles.vue, src/components/AddPeopleAndRoles/OrgPerson.vue, src/components/AddPeopleAndRoles/PeopleAndRoles.vue, src/components/DefineCompany/OfficeAddresses.vue, src/interfaces/stepper-interfaces/AddPeopleAndRole/org-person-interface.ts, src/resources/cooperative.ts, src/schemas/office-address-schema.ts, src/views/CreateShareStructure.vue, tests/unit/OrgPerson.spec.ts, tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#8661
- added disabled button + icon style overrides
- added disabled checkbox style overrides
- updated helper text
- added roles v-card
- conditionally hide CP role checkbox
- misc cleanup
- app version: 2.0.13
- created separate template blocks for person vs org
- moved business rules out of template and into script (getters)
- pre-select (lock) Director role if it's the only possibility
- make director's initial delivery address same as mailing address
- fixed unit test
=> 8661 Step 2 cleanup/enhancements

package-lock.json, package.json, src/components/AddPeopleAndRoles/OrgPerson.vue
*Issue #:* /bcgov/entity#8661
- simplified display logic (which fixes readonly state while editing org/person)
- app version 2.0.14
=> 8661 Simplified display logic

package-lock.json, package.json, src/components/DefineCompany/CooperativeType.vue, src/components/common/EntityInfo.vue, src/views/DefineCompany.vue
*Issue #:* /bcgov/entity#8514
- Minor Ux Updates to coop type
=> UX Updates

src/App.vue
*Issue #:* /bcgov/entity#8779
* Updated error handling for Account phone retrieval.
=> Updated Account Phone Error Handling

.github/workflows/ci.yml, Dockerfile, k8s/templates/bc.yaml
*Issue #:* /bcgov/entity#8609
- Updated node version
=> 8609 - Update node version

package-lock.json, package.json, src/components/DefineCompany/CooperativeType.vue, src/components/Summary/SummaryDefineCompany.vue, src/enums/coopType.ts, src/mixins/enum-mixin.ts, src/resources/cooperative.ts, src/store/getters/state-getters.ts, src/views/DefineCompany.vue, tests/unit/enum-mixin.spec.ts
*Issue #:* /bcgov/entity#8738
- updated Cooperative Type v-select items
- converted coop type on summary page
- changed Coop Type enum to type codes
- added helper to convert coop type to description
- added enum mixin unit test
- app version: 2.0.18
=> 8738 Changed Coop Type to a key

package-lock.json, package.json, src/components/AddPeopleAndRoles/PeopleAndRoles.vue, src/interfaces/stepper-interfaces/AddPeopleAndRole/org-person-interface.ts
*Issue #:* /bcgov/entity#8780
- Change email to not be null or empty
=> 8780 - Change email to not be null or empty

package-lock.json, package.json, src/assets/styles/overrides.scss, src/assets/styles/theme.scss, src/components/AddPeopleAndRoles/ListPeopleAndRoles.vue, src/components/CreateMemorandum/UploadMemorandum.vue, src/components/CreateRules/UploadRules.vue, src/components/CreateRules/UploadRulesSummary.vue, src/components/CreateShareStructure/ListShareClass.vue, src/components/IncorporationAgreement/AgreementType.vue, src/components/ReviewConfirm/Summary.vue, src/components/Summary/SummaryDefineCompany.vue, src/components/common/FileUploadPreview.vue, src/components/common/Stepper.vue, src/mixins/document-mixin.ts, src/store/actions/actions-model.ts, src/store/getters/state-getters.ts, src/store/mutations/mutations-model.ts
*Issue #:* /bcgov/entity#8432
* Implement validation success/failure scenarios for confirm & review step for upload rules
* Validation related updates for step 3(upload rules)
* addition of logic to track validation state for UI elements
* file upload validation error message tweaks
* addition of logic to detect failed upload
* update file upload component to support custom error messages for failed file uploads
* misc UI tweaks based off of UX feedback
* upload rules step(step 3)
* spacing 
* tooltip styling
* custom bullet
* alignment
* confirm and review step (step 5)
* spacing between sections
* validation success/failure display updates for upload rules section  
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this …
=> 8432 COOP IA upload review & confirm, rules validation and misc UI updates

src/components/CreateRules/UploadRules.vue
*Issue #:* /bcgov/entity#8432
* Minor spacing and operator clean up. *Hide White Space changes*
* Minor UX Updates
=> Upload Rules Ux

package-lock.json, package.json, src/mixins/name-request-mixin.ts, tests/unit/Actions.spec.ts
=> 8922 update to use NR State - CONSUMED, EXPIRED

package-lock.json, package.json, src/components/AddPeopleAndRoles/ListPeopleAndRoles.vue, src/components/AddPeopleAndRoles/OrgPerson.vue, src/components/AddPeopleAndRoles/PeopleAndRoles.vue, src/enums/incorporatorTypes.ts, tests/unit/Actions.spec.ts, tests/unit/App.spec.ts, tests/unit/ListPeopleAndRoles.spec.ts, tests/unit/OrgPerson.spec.ts
*Issue #:* /bcgov/entity#6742
- Changed organization terms; 
- Fixed tests.
** PLEASE DO NOT MERGE YET **
Legal-api changes need to be in sync.
=> 6742 - Changed organization terms

package-lock.json, package.json, src/interfaces/stepper-interfaces/AddPeopleAndRole/org-person-interface.ts, tests/unit/PeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#6742
- Changed orgName in OfficerIF
- Updated version
** This issue doesn't block the UI but keeps an extra property 'orgName' in the filing **
=> 6742 - Changed orgName in OfficerIF

src/mixins/legal-api-mixin.ts
*Issue #:* /bcgov/entity#8823
* Small adjustment to how the tasks are parsed from the API response.
=> Updated Dissolution Task Parsing

src/interfaces/stepper-interfaces/AddPeopleAndRole/org-person-interface.ts
*Issue #:* /bcgov/entity#6742
* Updated Empty officer IF
=> Updated OfficerIF

package-lock.json, package.json, src/App.vue, src/assets/styles/layout.scss, src/components/common/EffectiveDateTime.vue, src/interfaces/filing-interfaces/filing-interface.ts, src/mixins/filing-template-mixin.ts, src/mixins/legal-api-mixin.ts, src/store/state/state-model.ts, src/views/Dissolutions/DefineDissolution.vue, src/views/Dissolutions/ReviewConfirmDissolution.vue, tests/unit/ReviewConfirmDissolution.spec.ts
*Issue #:* /bcgov/entity#9051
This still has the component local to the project. The next step is to move the component to the bcrs-shared-components repo and then import it here.
- improved fee summary affix layout
- cleaned up App classes
- updated Dissolution Date and Time validation
- added prop to parse initial FED
- added support for saving/restoring null FED option
- added create methods to ignore loading changes
- app version: 3.0.15
=> 9051 Finished Effective Date Time integration

package-lock.json, package.json, src/views/Dissolutions/UploadAffidavit.vue
- fixed unsaved changes code re: UploadAffidavit component
- app version: 3.0.18
=> 8913 Fixed unsaved changes code

src/mixins/date-mixin.ts
- DateMixin.dateToPacificDate() is now compatible with the same method in our other projects
- This PR impacts nothing atm, but makes things in sync for possible future changes.
- This PR doesn't update the app version because it doesn't matter from a UI perspective.
=> Updated DateMixin to be compatible with other projects

package-lock.json, package.json, src/App.vue, tests/unit/App.spec.ts
*Issue #:* /bcgov/entity#9288
- Removed unit test warnings from App.spec.ts
=> 9288 - Removed unit test warnings from App.spec.ts

package-lock.json, package.json, src/views/Dissolutions/ReviewConfirmDissolution.vue
=> 9010 ux fix

package-lock.json, package.json, src/components/AddPeopleAndRoles/OrgPerson.vue, src/components/DefineDissolution/CustodianOfRecords.vue, src/interfaces/filing-interfaces/filing-interface.ts, src/interfaces/stepper-interfaces/AddPeopleAndRole/org-person-interface.ts, src/interfaces/store-interfaces/state-interfaces/dissolution-state-interface.ts, src/mixins/filing-template-mixin.ts, src/resources/Dissolutions/benefitCompany.ts, src/resources/Dissolutions/communityContributionCompany.ts, src/resources/Dissolutions/cooperative.ts, src/resources/Dissolutions/limitedCompany.ts, src/resources/Dissolutions/unlimitedCompany.ts, src/rules/first-name-rules.ts, src/rules/last-name-rules.ts, src/rules/org-name-rules.ts, src/store/state/state-model.ts, src/views/Dissolutions/DefineDissolution.vue, src/views/Dissolutions/ReviewConfirmDissolution.vue, tests/unit/CustodianOfRecords.spec.ts, tests/unit/OrgPerson.spec.ts
*Issue #:* /bcgov/entity#8910
* Updates Scroll to validations on DefineDissolutions
* Various UX updates for Custodians as seen here: https://github.com/bcgov/entity/issues/8910
* Applied current date to dissolution and role appointment date
* Updated v-models for text input to `trim` values instead of present user with leading or trailing white space errors. 
* Updated rules for names to catch white spaces with no characters
* Updated unit testing
*Note:* - All Ux Requests
=> Dissolutions ux, validation and filing json updates

src/components/common/TransactionalFolioNumber.vue, tests/jest-wrapper-factory.ts, tests/unit/ReviewConfirmDissolution.spec.ts, tests/unit/TransactionalFolioNumber.spec.ts
*Issue #:* /bcgov/entity#8930
- no app version change needed (no functional changes)
=> 8930 Updated unit tests

package-lock.json, package.json, src/App.vue, src/components/DefineDissolution/CustodianOfRecords.vue, src/components/common/EntityInfo.vue, src/interfaces/index.ts, src/interfaces/resource-interfaces/component-resource-interfaces/custodian-resource-interface.ts, src/interfaces/resource-interfaces/resource-interface.ts, src/interfaces/utils-interfaces/address-schema-interface.ts, src/resources/Dissolutions/benefitCompany.ts, src/resources/Dissolutions/communityContributionCompany.ts, src/resources/Dissolutions/cooperative.ts, src/resources/Dissolutions/limitedCompany.ts, src/resources/Dissolutions/unlimitedCompany.ts, src/schemas/office-address-schema.ts, src/store/getters/resource-getters.ts, src/store/getters/state-getters.ts, src/store/state/resource-model.ts, src/store/state/state-model.ts, src/views/Dissolutions/DefineDissolution.vue
*Issue #:* /bcgov/entity#8910
* Added override styling for BaseAddress class
* Updated logic to apply base address values from resources
* Apply address schemas based on type
* Fixed breadcrumb navigation for Dissolutions
* Updated resource files
* Applied Resource IF for custodians
* Added address schema IF
=> UX Updates for Custodians and EntityInfo header

package-lock.json, package.json, src/views/Incorporations/ReviewConfirm.vue
*Issue #:* /bcgov/entity#10147
* Added check to allow Corps to edit the Certify field.
=> Disable Certify for Coops Only

src/components/AddPeopleAndRoles/OrgPerson.vue
*Issue #:* /bcgov/entity#10147
* Added additional conditions to step 2. *Scope change
=> Release 3.0.3 additional conditions

package-lock.json, package.json, src/components/AddPeopleAndRoles/OrgPerson.vue, src/views/Dissolutions/ReviewConfirmDissolution.vue, src/views/Incorporations/ReviewConfirm.vue, tests/unit/ReviewConfirmDissolution.spec.ts
*Issue #:* /bcgov/entity#10147
* Implements changes from release 3.0.3b
* Removes staff condition on FED for CORPS
=> Completing Party and FED Updates

package-lock.json, package.json, src/components/CreateResolution/CompleteResolution.vue, src/components/common/NameRequestInfo.vue, src/mixins/auth-api-mixin.ts, src/mixins/date-mixin.ts, src/mixins/document-mixin.ts, src/mixins/legal-api-mixin.ts, src/mixins/name-request-mixin.ts, src/services/auth.services.ts, src/services/pay.services.ts, src/utils/axios-auth.ts, src/utils/config-helper.ts, src/views/Dissolutions/ReviewConfirmDissolution.vue, tests/unit/Actions.spec.ts, tests/unit/App.spec.ts, tests/unit/date-mixin.spec.ts, tests/unit/legal-api-mixin.spec.ts, tests/unit/mixin-tester.vue
*Issue #:* /bcgov/entity#10173
- renamed createUtcDateFromStr -> yyyyMmDdToDate 
- renamed dateStrToPacificDate -> yyyyMmDdToPacificDate
- deleted unused date mixin variable and method
- added date-mixin test file
- added legal-api-mixin test file
- added mixin-tester
- misc cleanup
- app version: 3.0.30
=> 10173 Misc date cleanup

package-lock.json, package.json, src/components/AddPeopleAndRoles/ListPeopleAndRoles.vue, src/components/common/Actions.vue, src/views/Incorporations/IncorporationAgreement.vue
*Issue #:* /bcgov/entity#10097
* Fixed Tooltip styling to make consistent through IA and Dissolutions.
* Fixed Redirect URL for Completed Dissolutions
=> Regression Testing Adjustments

src/components/CreateResolution/CompleteResolution.vue, src/components/CreateResolution/CompleteResolutionSummary.vue, src/components/CreateResolution/index.ts, src/mixins/filing-template-mixin.ts, src/resources/Dissolutions/cooperative.ts, src/rules/common-rules.ts, src/rules/date-rules.ts, src/rules/index.ts, src/views/Dissolutions/ReviewConfirmDissolution.vue, tests/unit/ReviewConfirmDissolution.spec.ts
* Remaining outstanding issues from previous PR (https://github.com/bcgov/business-create-ui/pull/300)
* Move date and other validation rules to rules files to make reusable
* Move resolution summary in review page to own component(`CompleteResolutionSummary`)
* Restructure/simplify parseDissolutionDraft logic for parsing special resolutions
* Misc cleanup 
=> 8913 vd special resolutions additional updates, misc clean-up, ux feedback updates

package-lock.json, package.json, src/components/CreateResolution/CompleteResolution.vue, src/rules/date-rules.ts
* Imported/applied update DatePicker component
* Minor prop updates for new DatePicker Version
=> DatePicker UX Implementations

package-lock.json, package.json, src/assets/styles/base.scss, src/components/Affidavit/Affidavit.vue, src/components/CreateResolution/CompleteResolution.vue, src/components/CreateResolution/CompleteResolutionSummary.vue, src/main.ts, src/resources/Dissolutions/benefitCompany.ts, src/resources/Dissolutions/communityContributionCompany.ts, src/resources/Dissolutions/limitedCompany.ts, src/resources/Dissolutions/unlimitedCompany.ts, tests/jest-wrapper-factory.ts, tests/unit/CompleteResolution.spec.ts, tests/unit/ReviewConfirmDissolution.spec.ts
* UXA feedback updates
* Added tests for `CompleteResolution` component
* misc cleanup
=> 8913 vd special resolution uxa feedback updates

package-lock.json, package.json, src/components/CreateResolution/CompleteResolution.vue, src/rules/date-rules.ts
=> Date validation bug fix

package-lock.json, package.json, src/components/CreateResolution/CompleteResolution.vue
* Update to use v1.1.9 of shared component date picker.  This component has been updated to use the desired format of `November 30, 2021` as opposed to `Nov 30, 2021`.
* Update date validation error messaged to also use same date format as date picker display date.
* bumped app version num
=> 8913 vd special resolution uxa feedback: date format related updates

package-lock.json, package.json
*Issue #:* /bcgov/entity#10333
* Updated App version to reflect a major change in the UI with the introduction of Dissolutions.
* Updated EffectiveDate dependency to incorporate recent validation rule updates.
=> Updated App and Dependency versions

package-lock.json, package.json, src/assets/styles/overrides.scss, src/store/getters/state-getters.ts, tests/unit/ReviewConfirmDissolution.spec.ts
*Issue #:* /bcgov/entity#10394 && /bcgov/entity#10395
* Fixed logic on when to apply EffectiveDate validations, removed Staff Only clause.
* Update v-card-title with word break to override base vuetify styling of `break all`.
=> Validation and Label fixes

package-lock.json, package.json, src/App.vue, src/resources/Dissolutions/benefitCompany.ts, src/resources/Dissolutions/cooperative.ts, src/views/Dissolutions/DefineDissolution.vue, src/views/Dissolutions/ReviewConfirmDissolution.vue
*Issue #:* /bcgov/entity#10448
* Updated text content for information banner and custodian description.
* Updated text in EffectiveDateTime help content.
=> Text Fixes and Updates

package-lock.json, package.json, src/App.vue, src/components/common/EntityInfo.vue, src/components/common/index.ts, src/interfaces/index.ts, src/resources/BreadCrumbResource.ts, src/resources/breadCrumbResource.ts, src/resources/index.ts, tests/unit/entityInfo.spec.ts
*Issue #:* /bcgov/entity#10235
* Implemented Shared BreadCrumb
* Removes obsolete code
* Updated tests
=> Implemented Shared BreadCrumb

src/components/common/FileUploadPreview.vue, src/mixins/document-mixin.ts, tests/unit/FileUploadPreview.spec.ts
*Issue #:* /bcgov/entity#9987
Updated the max file size in document mixin
Updated the validation error message
Updated the test
=> Change file upload size to 30MB

package-lock.json, package.json, src/App.vue
*Issue #:* /bcgov/entity#10576
* Minor Ux update - modified text used in breadcrumb
* Updated to latest breadcrumb version
=> Breadcrumb Ux Update

package-lock.json, package.json, src/App.vue, src/assets/styles/theme.scss, src/components/CreateResolution/CompleteResolution.vue, src/components/common/ContactInfo.vue, src/components/common/index.ts, src/components/dialogs/FetchErrorDialog.vue, src/components/dialogs/FileAndPayInvalidNameRequestDialog.vue, src/components/dialogs/PaymentErrorDialog.vue, src/components/dialogs/SaveErrorDialog.vue, src/enums/roleTypes.ts, src/mixins/filing-template-mixin.ts, src/views/Dissolutions/ReviewConfirmDissolution.vue, tests/unit/ContactInfo.spec.ts, tests/unit/FetchErrorDialog.spec.ts, tests/unit/PaymentErrorDialog.spec.ts, tests/unit/SaveErrorDialog.spec.ts
*Issue #:* /bcgov/entity#9529
* Refactors to support Dissolution Staff Filings
* Add staff payment flow for dissolutions (but not IAs)
* Validation fixes on Step 2 when resuming from save or pay failure
* Fix issue with Court Order / POA not meeting schema requirements
* Updated unit tests 
* Updated theme to match Filings UI
* edit/renamed Contact Info Component
=> Dissolutions staff support and payment flow

devops/vaults.json, package-lock.json, package.json, public/config/configuration.json, src/App.vue, src/resources/BreadCrumbResource.ts, src/utils/config-helper.ts
*Issue #:* /bcgov/entity#10747
* Added configuration for BCROS Home Url
* Updated Home Crumb for non-staff
*NOTE:* - The updated routes require additional in configuration in DEV, TEST, PROD ENV's to add the following:
Dev = https://yfthig-dev.web.app/
Test = https://www.bcregistry.daxiom.ca/
Prod = https://www.bcregistry.gov.bc.ca/
=> Updated home crumb and config

package-lock.json, package.json, src/App.vue, src/components/index.ts, tests/unit/App.spec.ts
*Issue #:* /bcgov/entity#10922
* Updated CC version
* Minor refactors to resolve Unit test breakages
=> Updated CC version + minor refactors

package-lock.json, package.json, src/resources/Dissolutions/cooperative.ts
*Issue #:* /bcgov/entity#10581
=> 10581 update tooltip text in coop voluntary dissolution

src/App.vue
*Issue #:* /bcgov/entity#10999
- init app at end of create(), not on initial route change
- no need to update version number since the deployed app is currently broken and it will be obvious when the fix is deployed :)
=> 10999 Fixed init bug

package-lock.json, package.json, src/App.vue, src/components/DefineRegistration/DefineRegistrationSummary.vue, src/components/DefineRegistration/StartDate.vue, src/views/Registrations/DefineRegistration.vue, tests/unit/StartDate.spec.ts
*Issue #:* /bcgov/entity#9721
* Added start date validations & prompts
* Update error text
=> Start Date UX updates - Validations

package-lock.json, package.json, src/components/Dissolution/AssociationDetails.vue, src/utils/feature-flags.ts
*Issue #:* /bcgov/entity#9245
- fixed incorrect event name
- added default "registration" FF
- app version = 3.3.4
=> 9245 Fixed contact info not updated

package-lock.json, package.json, src/components/Dissolution/CompleteResolution.vue
*Issue #:* /bcgov/entity#9245
- added conditional chaining to date picker refs to avoid dereferencing them before they are created
- app version = 3.3.5
=> 9245 Fixed some resolution page errors

package-lock.json, package.json, src/App.vue
*Issue #:* /bcgov/entity#9518
- if need to reroute, return instead of continue
- app version = 3.4.3
=> 9518 Fix multiple getData()

package-lock.json, package.json, src/App.vue, src/components/Dissolution/CompleteAffidavit.vue, src/components/Dissolution/CompleteResolution.vue, src/views/Registration/RegistrationReviewConfirm.vue
*Issue #:* /bcgov/entity#9518 and /bcgov/entity#11382
- removed previous debugging statements
- enabled validation styles on registration document delivery component
- allowed SbcStaff to edit registration document delivery completing party
- allowed SbcStaff to edit registration staff certified by
- allowed SbcStaff to see registration staff certify statement
- allowed SbcStaff to bypass email and phone  checks on app init
- fixed error handling in App
- app version = 3.4.4
=> 9518 Removed debug code + fixed App error handling + prep for Sbc Staff registrations

devops/vaults.json
=> Add naics-api to vault

package-lock.json, package.json, src/assets/styles/theme.scss, src/components/Registration/NaicsHelpText.vue, src/components/Registration/NaicsResult.vue, src/components/Registration/NatureOfBusiness.vue, src/interfaces/Registration/naics-interfaces.ts, src/interfaces/index.ts, src/services/naics.services.ts, tests/unit/NaicsHelpText.spec.ts, tests/unit/NaicsResult.spec.ts, tests/unit/NatureOfBusiness.spec.ts, tests/unit/test-data/naics.json
*Issue #:* /bcgov/entity#9518
- updated sbc-common-components dependency (v42)
- formatted NAICS Result
- updated Change button
- added interfaces
- app version = 3.4.6
=> 9518 Updated NAICS result formatting

package-lock.json, package.json, src/components/Registration/NaicsResult.vue, src/components/Registration/NatureOfBusiness.vue, src/components/common/NameRequestInfo.vue
*Issue #:* /bcgov/entity#11474
- updated column breakpoints (3/9 vs 2/10)
- added Select button to NAICS results
- updated hint text
- app version = 3.4.7
=> 11474 Misc UI updates

package-lock.json, package.json, src/components/Dissolution/AssociationDetails.vue, src/components/Dissolution/CompleteResolution.vue, src/components/Dissolution/CustodianOfRecords.vue, src/components/Dissolution/DestroyCertificate.vue, src/components/Dissolution/DissolutionStatement.vue, src/components/Registration/BusinessAddresses.vue, src/components/common/BusinessContactInfo.vue, src/components/common/ListPeopleAndRoles.vue, src/components/common/NameRequestInfo.vue, src/components/common/OfficeAddresses.vue, src/views/Dissolution/DissolutionReviewConfirm.vue, src/views/Incorporation/IncorporationAgreement.vue
*Issue #:* /bcgov/entity#11474
- more whitespace tweaks
- hid some labels below size "sm"
=> 11474 More whitespace tweaks after testing in Dev

package-lock.json, package.json, src/components/common/DocumentDelivery.vue, src/views/Dissolution/DissolutionReviewConfirm.vue, src/views/DissolutionFirm/DissolutionFirm.vue, src/views/Incorporation/IncorporationReviewConfirm.vue, src/views/Registration/RegistrationReviewConfirm.vue, tests/unit/DocumentDelivery.spec.ts
*Issue #:* /bcgov/entity#11408
* Added additional label and additional email field 
=> Document Delivery: Shared component#11408

package-lock.json, package.json, src/assets/styles/overrides.scss, src/components/Registration/RegPeopleAndRoles.vue, src/components/common/PeopleAndRoles.vue, src/mixins/add-edit-org-person-mixin.ts, src/mixins/people-roles-mixin.ts, src/resources/Registrations/soleProprietorship.ts, src/views/DissolutionFirm/DissolutionFirm.vue, src/views/Registration/RegistrationReviewConfirm.vue, tests/unit/AddEditOrgPerson.spec.ts, tests/unit/RegAddEditOrgPerson.spec.ts
*Issue #:* /bcgov/entity#11573
- changed disabled checkboxes to blue
- updated whitespace around button panel
- updated BN rules
- fixed delivery address incomplete code
- prepared for GP (ie, partners)
- fixed typo
- display proprietor/partners in Doc Delivery section
- fixed unit test helpers so errors display in the tests themselves
- app version = 3.5.4
=> 11573 Misc fixes

package-lock.json, package.json, src/App.vue, src/assets/styles/overrides.scss, src/components/Registration/HelpContactUs.vue, src/components/Registration/RegAddEditOrgPerson.vue, src/components/Registration/RegPeopleAndRoles.vue, src/components/common/AddEditOrgPerson.vue, src/components/common/ListPeopleAndRoles.vue, src/components/common/PeopleAndRoles.vue, src/mixins/add-edit-org-person-mixin.ts
*Issue #:* /bcgov/entity#11573
- added Help Contact Us component
- updated manual business add code
- removed truncated name with tooltip
- implemented section validation (WIP)
- updated Actions whitespace per UXA
- updated disabled checkbox label per UXA
- updated yellow v-card corners per UXA
- updated P&R list icon colors per UXA
- capitalized P&R list company names per UXA
- disabled P&R list actions only per UXA
- updated P&R list action sizes per UXA
- updated P&R whitespace per UXA
- updated subheader colors per UXA
- updated P&R button heights per UXA
- app version = 3.5.5
=> 11573 UXA tweaks + incremental P&R manual business entry

package-lock.json, package.json, src/App.vue
*Issue #:* /bcgov/entity#11751
* Added valid business identifiers for SP and GP (starting with FM)
=> Added valid business identifiers for SP and GP starting with FM

package-lock.json, package.json, src/components/Registration/RegAddEditOrgPerson.vue, src/components/Registration/RegPeopleAndRoles.vue, src/components/common/AddEditOrgPerson.vue, src/components/common/ListPeopleAndRoles.vue, src/components/common/PeopleAndRoles.vue, src/mixins/add-edit-org-person-mixin.ts, tests/unit/AddEditOrgPerson.spec.ts, tests/unit/RegAddEditOrgPerson.spec.ts
*Issue #:* /bcgov/entity#11573
- display person email/IN/BN in reg only
- enabled component rules only after user clicks Done
- updated P&R list icon colors
- app version = 3.5.9
=> 11573 Misc UX updates

package-lock.json, package.json, src/components/Registration/HelpContactUs.vue, src/components/Registration/RegAddEditOrgPerson.vue, src/components/Registration/RegPeopleAndRoles.vue, src/components/common/AddEditOrgPerson.vue, src/components/common/ListPeopleAndRoles.vue, src/enums/roleTypes.ts, src/interfaces/stepper-interfaces/AddPeopleAndRole/org-person-interface.ts, src/mixins/add-edit-org-person-mixin.ts, src/mixins/people-roles-mixin.ts, src/views/Registration/RegistrationReviewConfirm.vue, tests/unit/AddEditOrgPerson.spec.ts, tests/unit/HelpBusinessNumber.spec.ts, tests/unit/HelpContactUs.spec.ts, tests/unit/ListPeopleAndRoles.spec.ts, tests/unit/RegAddEditOrgPerson.spec.ts, tests/unit/RegPeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#11573
- deleted unneeded code
- changed some ids to classnames
- app version = 3.5.10
=> 11573 A bunch of unit tests

package-lock.json, package.json, src/interfaces/filing-interfaces/filing-interface.ts, src/mixins/filing-template-mixin.ts, src/services/legal.services.ts, tests/unit/filing-template-mixin.spec.ts, tests/unit/test-data/registration.json
*Issue #:* /bcgov/entity#11569
=> 11569 businessOffice schema update

package-lock.json, package.json, src/components/Registration/BusinessNumber.vue, src/components/Registration/RegAddEditOrgPerson.vue, src/components/Registration/RegPeopleAndRoles.vue, src/components/common/ListPeopleAndRoles.vue, src/components/common/PeopleAndRoles.vue, src/mixins/add-edit-org-person-mixin.ts
*Issue #:* /bcgov/entity#10891
- fixed p font size in P&R table
- added mask to Business Number (for GP and SP org-persons)
- ignored rule for adding partners
- enabled validation from start if editing
- fixed address form validation not affecting main form on submit
- app version = 3.5.14
=> 10891 Misc UI/UX updates/fixes

package-lock.json, package.json, src/App.vue, src/components/common/EntityInfo.vue, src/interfaces/index.ts, src/mixins/date-mixin.ts, src/mixins/index.ts, src/views/DissolutionFirm/DissolutionFirm.vue, tests/unit/App.spec.ts
There is something quite broken with the commits in the PR that I am reverting. (Possibly a rebase issue somewhere.)
I created a local branch with the same commits as bcgov/main, ran `npm install`, and then got a million errors on `npm run serve`. I checked out Faiz's PR (`gh pr checkout 374`) and tried to run it -- same issues. I tried to remove the latest commits locally to see which commit broke things, and saw total chaos in the commit history.
So I'm reverting bcgov/business-create-ui#374. (I pulled PR 377's commit into a local branch that had been synced with bcgov/main and saw no issues.)
Sorry @shabeeb-aot . Your branch still exists (and I have a copy of it as well). My approach now will be to start with a clean branch and add in your code changes manually. If that works then I …
=> Revert "Staff View: Dissolution Filing SP/GP#11411 | comments"

package-lock.json, package.json, src/App.vue, src/components/common/EntityInfo.vue, src/interfaces/index.ts, src/mixins/date-mixin.ts, src/mixins/index.ts, src/views/DissolutionFirm/DissolutionFirm.vue, tests/unit/App.spec.ts
**These are the code changes from PR #374 , which had some corrupt commits and was reverted in #377 .**
*Issue #:* /bcgov/entity#11411
- Added staff comments
- Redirection for SP/GP filing from App.vue
=> 11411 Firm dissolution staff comments

package-lock.json, package.json, src/components/Incorporation/UploadRules.vue, src/components/Registration/BusinessTypeConfirm.vue, src/components/Registration/DefineRegistrationSummary.vue, src/interfaces/store-interfaces/state-interfaces/registration-state-interface.ts, src/mixins/common-mixin.ts, src/mixins/filing-template-mixin.ts, src/store/actions/actions-model.ts, src/store/mutations/mutations-model.ts, src/store/state/state-model.ts, src/views/Registration/RegistrationDefineBusiness.vue, tests/unit/filing-template-mixin.spec.ts, tests/unit/test-data/registration.json
Issue #: /[bcgov/business-create-ui#9828](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/9828)
Description of changes:
- for GP only, add Business Type component with checkbox (see comments below)
design: https://projects.invisionapp.com/share/3511UPXPMT2P#/screens/459770324
Issue #: /[bcgov/business-create-ui#11470](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/11470)
Description of changes:
- The Cooperative name is identified exactly as follows throughout the `Memorandum` --> `Rules of the Association`
=> 9828/11470 Collateral Fix GP Create UI Business Type checkbox/Coop Incorporation - Rules

package-lock.json, package.json, src/components/Registration/RegAddEditOrgPerson.vue, src/components/Registration/RegPeopleAndRoles.vue, src/components/common/AddEditOrgPerson.vue, src/components/common/ListPeopleAndRoles.vue, src/components/common/PeopleAndRoles.vue, src/mixins/add-edit-org-person-mixin.ts, src/mixins/people-roles-mixin.ts, tests/unit/AddEditOrgPerson.spec.ts, tests/unit/RegAddEditOrgPerson.spec.ts, tests/unit/SbcFeeSummary.spec.ts
*Issue #:* /bcgov/entity#11913
- added lookup/manual toggle
- added initial lookup text
- replaced activeIndex -1 by NaN
- some lint fixes
- added unit tests
- app version = 3.5.18
=> 11913 Initial business lookup panel

package-lock.json, package.json, src/components/common/ListPeopleAndRoles.vue, src/enums/roleTypes.ts, src/interfaces/filing-interfaces/filing-interfaces.ts, src/interfaces/filing-interfaces/party-interface.ts, src/interfaces/index.ts, src/interfaces/stepper-interfaces/AddPeopleAndRole/org-person-interface.ts, src/mixins/filing-template-mixin.ts, tests/unit/BusinessTypeConfirm.spec.ts, tests/unit/filing-template-mixin.spec.ts
*Issue #:* /bcgov/entity#11977
- deleted obsolete officer incorp number
- deleted obsolete role type Subscriber
- added Party and ApiPerson interfaces
- build/parse filing using correct schema
- converted party <-> orgPerson
- fixed lint issues
- app version = 3.5.21
=> 11977 Fixed proprietor tax id (business number)

package-lock.json, package.json
*Issue #:* /bcgov/entity#12088
- imported latest sbc-common-components (2.4.46)
- app version = 4.0.3
=> 12088 Imported latest sbc-common-component

package-lock.json, package.json, src/components/Dissolution/AssociationDetails.vue, src/interfaces/filing-interfaces/party-interface.ts, src/mixins/filing-template-mixin.ts, src/store/actions/actions-model.ts, src/store/getters/state-getters.ts, src/store/mutations/mutations-model.ts, src/views/DissolutionFirm/DissolutionFirm.vue
*Issue #:* /bcgov/entity#11410
* SP/GP filing save changes
* remove validation for unused components in SP/GP
* Dissolution date select and send in API
*
=>  File Now: Validation for Dissolution FIling#11410

package-lock.json, package.json, src/App.vue, src/resources/Dissolutions/generalPartnership.ts, src/resources/Dissolutions/index.ts, src/resources/index.ts
*Issue #:* /bcgov/entity#11659
* Resource file for GP
* Dissolution for GP
=>  dissolution changes for GP

package-lock.json, package.json, src/mixins/filing-template-mixin.ts, tests/unit/PaymentErrorDialog.spec.ts, tests/unit/filing-template-mixin.spec.ts
*Issue #:* /bcgov/entity#12263
- deleted empty tax id so it doesn't fail schema pattern
- added unit tests
- fixed lint error
- app version = 4.0.7
=> 12263 Fixed empty tax id bug

package-lock.json, package.json, src/App.vue
- added business check before loading parties
- app version = 4.0.9
=> Added business check before loading parties

package-lock.json, package.json, src/App.vue
*Issue #:* /bcgov/entity#11660
* Pass new filingLabelText to feeSumary component for SP/GP
=> pass filingLabelText prop to feeSummary Component

package-lock.json, package.json, src/App.vue, src/views/DissolutionFirm/DissolutionFirm.vue
*Issue #:* https://github.com/bcgov/entity/issues/12324
Added Display Banner message for SP and GP on Create UI
=> Feature: 12324 Display Banner message for SP and GP on Create UI

nginx.conf
=> 9260 include *.apigee.net in CSP

package-lock.json, package.json, src/components/Registration/BusinessLookup.vue, src/components/Registration/RegAddEditOrgPerson.vue, src/components/Registration/RegPeopleAndRoles.vue, src/interfaces/stepper-interfaces/AddPeopleAndRole/org-person-interface.ts, src/mixins/add-edit-org-person-mixin.ts, src/services/legal.services.ts, tests/unit/BusinessLookup.spec.ts, tests/unit/RegAddEditOrgPerson.spec.ts
*Issue #:* /bcgov/entity#10885
=> 10885 populate selected business from lookup

package-lock.json, package.json, src/mixins/add-edit-org-person-mixin.ts
*Issue #:* /bcgov/entity#10885
=> 10885 reset all data

package-lock.json, package.json
*Issue #:* /bcgov/entity#12309
- updated Business Lookup import
- app version = 4.0.19
=> 12309 Updare Business Lookup import

package-lock.json, package.json
*Issue #:* [/bcgov/entity#12464](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/12464)
- Update Sbc Common Components dependency version to a minimum of 2.4.52
=> 12464 Create UI: Entities to pick up new footer which includes hours of availability

package-lock.json, package.json, src/components/common/Stepper.vue
*Issue #:* /bcgov/entity#11736
Fix for incomplete pull request #407
- Step icons are now marked incomplete after visiting the Review and Confirm step
-  App version = 4.0.21
=> Change verification to show step icons as incomplete 11736

package-lock.json, package.json, src/services/business-lookup.services.ts
*Issue #:* /bcgov/entity#12758
- provided fallback for account id
- app version = 4.0.22
=> 12758 Fixed missing account id

package-lock.json, package.json, src/components/common/TransactionalFolioNumber.vue, src/mixins/add-edit-org-person-mixin.ts, src/services/business-lookup.services.ts
*Issue #:* /bcgov/entity#12757
- changed TFN to valid when input ref is undefined
- cleared invalid BN (length < 9)
- filtered out search results without valid identifier
- app version = 4.1.0
=> 12757 Fixed TFN validation + added safety checks

package-lock.json, package.json, src/components/common/Actions.vue, src/store/getters/state-getters.ts
*Issue #:* /bcgov/entity#12481
resolved form submission bug, add condition to check date field
=> Bug 12481: Error while filling a dissolution

package-lock.json, package.json, public/config/configuration.json, src/services/legal.services.ts, src/store/getters/state-getters.ts, src/utils/config-helper.ts
*Issue #:* [/bcgov/entity#12307](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/12307)
- renamed url in `legal.services.ts`
- renamed `legalApiUrl` in `config-helper.ts`
=> 12307 Update business-create-ui to use legal API to V2

package-lock.json, package.json, src/rules/first-name-rules.ts, src/rules/middle-name-rules.ts, tests/unit/AddEditOrgPerson.spec.ts
*Issue #:* [/bcgov/entity#13058](https://app.zenhub.com/workspaces/entities-team-space-6143567664fb320019b81f39/issues/bcgov/entity/13058)
- change the max length of "firstName" to 20
- change UI before the schema change
=> 13058 COLIN API failure - Front and Backend Change validation of the first name field in Coop IA UI and/or Corp Party table

package-lock.json, package.json, src/components/Registration/BusinessNumber.vue, src/components/Registration/DefineRegistrationSummary.vue, src/components/Registration/RegAddEditOrgPerson.vue, src/components/Registration/RegPeopleAndRoles.vue, src/components/common/AddEditOrgPerson.vue, src/interfaces/filing-interfaces/filing-interfaces.ts, src/interfaces/stepper-interfaces/AddPeopleAndRole/org-person-interface.ts, src/interfaces/store-interfaces/state-interfaces/registration-state-interface.ts, src/mixins/add-edit-org-person-mixin.ts, src/mixins/filing-template-mixin.ts, src/mixins/people-roles-mixin.ts, src/services/business-lookup-services.ts, src/store/actions/actions-model.ts, src/store/mutations/mutations-model.ts, src/store/state/state-model.ts, src/views/Registration/RegistrationDefineBusiness.vue, tests/unit/AddEditOrgPerson.spec.ts, tests/unit/DissolutionFirm.spec.ts, tests/unit/RegAddEditOrgPerson.spec.ts, tests/unit/business-lookup-services.spec.ts, tests/unit/filing-template-mixin.spec.ts
*Issue #:* /bcgov/entity#12911, /bcgov/entity#13145
=> 12911 moved business number to step 1 for SP

package-lock.json, package.json, src/components/Registration/DefineRegistrationSummary.vue, src/views/Registration/RegistrationDefineBusiness.vue
*Issue #:* bcgov/entity#12306
- commented out Folio or Reference Number
- app version = 4.1.9
=> 12306 Commented out Folio or Reference Number

package-lock.json, package.json, src/mixins/filing-template-mixin.ts
*Issue #:* bcgov/entity#13344
- handle null business object in initial draft
- app version = 4.1.10
=> 13344 Handle null business object in initial draft

package-lock.json, package.json, src/components/common/Actions.vue, tests/unit/Actions.spec.ts
*Issue #:* bcgov/entity#10495
- added Filing ID to Return URL
- app version = 4.1.11
=> 10495 Added Filing ID to Return URL

package-lock.json, package.json, src/components/common/BusinessContactInfo.vue
*Issue #:* /bcgov/entity#13371
=> 13371 Create UI: Phone extension visual should remain "optional" until value entered

src/components/common/BusinessContactInfo.vue, src/rules/phone-rules.ts
*Issue #:* /bcgov/entity#13371
- added text "(Optional)" to phone number
- removed the mandatory rule
=> 13371 Create UI: Phone number field remains optional

package-lock.json, package.json, src/components/Dissolution/CompleteResolution.vue, src/components/Incorporation/IncorporationDateTime.vue, src/components/Registration/StartDate.vue, src/mixins/filing-template-mixin.ts, src/rules/date-rules.ts, src/views/DissolutionFirm/DissolutionFirm.vue, tests/unit/App.spec.ts, tests/unit/CompleteResolution.spec.ts, tests/unit/IncorporationDateTime.spec.ts
*Issue #:* bcgov/entity#11783
- changed "new Date()" to use internal values and better mixin methods
- misc cleanup
- fixed some unit tests
- app version = 4.1.15
=> 11783 Get rid of "new Date()"

package-lock.json, package.json, src/components/Registration/RegAddEditOrgPerson.vue, src/mixins/people-roles-mixin.ts, tests/unit/RegAddEditOrgPerson.spec.ts
*Issue #:* /bcgov/entity#12444
- updated texts
=> 12444 Verify - Create UI SP/GP changes

package-lock.json, package.json, src/components/Incorporation/UploadMemorandum.vue, src/components/Incorporation/UploadRules.vue, src/components/Registration/RegPeopleAndRoles.vue, src/resources/Incorporations/cooperative.ts, tests/unit/UploadRules.spec.ts
*Issue #:* /bcgov/entity#9269
- updated step 3 & 4 texts
=> 9269 Create UI - Cooperative Updates to Step 3 & 4 text

devops/vaults.json
*Issue #:* bcgov/entity#12985
- added webchat vault
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the namerequest license (Apache 2.0).
=> 12985 Changed vaults.json

package-lock.json, package.json, src/interfaces/store-interfaces/state-interfaces/org-information-interface.ts, src/store/getters/state-getters.ts
*Issue #:* bcgov/entity/issues/13412
Support for SBC-Staff
=> Feature 13412 - Support for SBC-Staff

package-lock.json, package.json, src/enums/accountTypes.ts, src/store/getters/state-getters.ts, src/views/DissolutionFirm/DissolutionFirm.vue
*Issue #:* /bcgov/entity#13822
=> sp/gp diss - completing party editable for sbc staff

package-lock.json, package.json, src/App.vue
*Issue #:* /bcgov/entity#13861
Update SBC-common-components
=> 13861 - Update business-create-ui to use sbc-common-components 3.0.3.

package-lock.json, package.json
*Issue #:* /bcgov/entity#13875
- Updated NOB shared component which now emits upon building filing from save
- version 4.3.3
- related [bcrs PR](https://github.com/bcgov/bcrs-shared-components/pull/153)
=> 13875 update NOB import

package-lock.json, package.json, src/views/Incorporation/IncorporationAgreement.vue, tests/unit/App.spec.ts, tests/unit/FetchErrorDialog.spec.ts, tests/unit/HelpContactUs.spec.ts, tests/unit/NameRequestInfo.spec.ts, tests/unit/PaymentErrorDialog.spec.ts, tests/unit/RegPeopleAndRoles.spec.ts, tests/unit/SaveErrorDialog.spec.ts, tests/unit/TransactionalFolioNumber.spec.ts
*Issue #:* bcgov/entity#13232
- upgraded vue test-utils to v1.3.3
- replaced "find()" by "findComponent()" where needed
- app version = 4.3.9
=> 13232 Upgraded vue-test-utils

package-lock.json, package.json, src/components/Incorporation/SummaryDefineCompany.vue, src/components/common/ListNameTranslations.vue, src/components/common/NameRequestInfo.vue
*Issue #:* bcgov/entity##13445
- display name translations in upper case (like Edit UI)
- fixed separator bar colours
- fixed a typo
- app version = 4.3.12
=> 13445 Changes backported from Edit UI + small fixes

package-lock.json, package.json, src/interfaces/resource-interfaces/resource-interface.ts, src/resources/Incorporations/benefitCompany.ts, src/resources/Incorporations/communityContributionCompany.ts, src/resources/Incorporations/cooperative.ts, src/resources/Incorporations/limitedCompany.ts, src/resources/Incorporations/unlimitedCompany.ts, src/store/getters/resource-getters.ts, src/store/state/resource-model.ts, src/views/Incorporation/IncorporationDefineCompany.vue, src/views/Incorporation/IncorporationReviewConfirm.vue, tests/unit/IncorporationDefineCompany.spec.ts, tests/unit/IncorporationReviewConfirm.spec.ts
*Issue #:* /bcgov/entity#14140
- Deleted statement template tag in Define Your Company and Review and Confirm steps
- Deleted "title", "description" and "statement" fields in the resource files
- Modified unit test files for the deleted statement template tag
=> 14140 Delete Statements Altogether

package-lock.json, package.json, src/App.vue
*Issue #:* /bcgov/entity/issues/14301
Support for SBC Staff
=> Feature 14301 - SBC changes related to Completing party and Certify section for SP/GP Change filings and Dissolution

package-lock.json, package.json, src/components/common/NameRequestInfo.vue, src/utils/Capitalize.ts, src/utils/index.ts, tests/unit/NameRequestInfo.spec.ts
*Issue #:* bcgov/entity#14403
- capitalized NR status (to match Filings UI)
- added util file
- app version = 4.3.20
=> 14404 Capitalized NR status

package-lock.json, package.json, src/services/business-lookup-services.ts, tests/unit/business-lookup-services.spec.ts
*Issue #:* bcgov/entity#14505
- removed SP from list of legal types to search for
- app version = 4.3.21
=> 14505 Removed SP from business lookup

package-lock.json, package.json, public/config/configuration.json, src/main.ts, src/utils/FetchConfig.ts
**This code change is for testing only, since it must deployed on a real URL (cannot use localhost). I am merging this into a special branch that I will deploy to Dev directly. So this code isn't going into main branch yet, and the next main branch deployment will overwrite Dev. I will work with Vysakh to ensure this doesn't accidentally get deployed to Test :)**
- added vue-hotjar package
- added Hotjar ID to config (only temporary -- it needs to be '' by default and provided by 1Password/config map)
- initialized Hotjar
- app version = 4.4.0
=> 14429 Enable Hotjar - special branch for testing only

package-lock.json, package.json, src/components/common/AgreementType.vue
*Issue #:* /bcgov/entity#14473
Fix - Review and Confirm step incorporation agreement section now displays only the summary description of selected agreement choice.
=> 14473-CCC, ULC BEN, BC Incorporation agreement step is not reflected correctly in Review and Confirm step

package-lock.json, package.json, src/App.vue, src/components/common/AddEditOrgPerson.vue, src/components/common/PeopleAndRoles.vue, src/enums/restorationTypes.ts, src/interfaces/stepper-interfaces/AddPeopleAndRole/people-and-roles-resource-interface.ts, src/mixins/add-edit-org-person-mixin.ts, src/mixins/filing-template-mixin.ts, src/mixins/people-roles-mixin.ts, src/resources/Incorporation/BC.ts, src/resources/Incorporation/BEN.ts, src/resources/Incorporation/CC.ts, src/resources/Incorporation/ULC.ts, src/resources/Restoration/BC.ts, src/resources/Restoration/BEN.ts, src/resources/Restoration/CC.ts, src/resources/Restoration/ULC.ts, src/store/actions/actions-model.ts, src/store/getters/resource-getters.ts, src/store/getters/state-getters.ts, src/store/mutations/mutations-model.ts, src/store/state/resource-model.ts, src/views/Restoration/RestorationReviewConfirm.vue, tests/unit/AddEditOrgPerson.spec.ts, tests/unit/RegAddEditOrgPerson.spec.ts
*Issue #:* bcgov/entity#14798
- cleaned up feeFilingData re: Coop dissolutions
- implemented multiple rolesSubtitle
- parsed restoration data
- updated resources for multiple filingData and rolesSubtitle
- removed unneeded addIncorporator logic
- added disable role getters
- added restoration actions/mutations
- added restoration getters
- added StaffPayment to restoration last step (to test things)
- fixed a unit test
- app version = 4.5.4
=> 14798 Added applicant information (incremental)

package-lock.json, package.json, src/App.vue, src/assets/styles/base.scss, src/dialogs/AccountAuthorizationDialog.vue, src/dialogs/FetchErrorDialog.vue, src/dialogs/FileAndPayInvalidNameRequestDialog.vue, src/dialogs/FilingSurveyDialog.vue, src/dialogs/InvalidFilingDialog.vue, src/dialogs/InvalidRouteDialog.vue, src/dialogs/NameRequestInvalidErrorDialog.vue, src/dialogs/SaveErrorDialog.vue, src/dialogs/index.ts, tests/unit/FilingSurveyDialog.spec.ts, tests/unit/NameRequestInvalidErrorDialog.spec.ts
- added Filing Survey dialog
- renamed class "genErr" -> "font-14"
- app version = 4.5.6
- still WIP but safe to deploy
=> 14429 Filing Survey dialog (incremental)

devops/vaults.json, package-lock.json, package.json, public/config/configuration.json, src/App.vue, src/dialogs/FilingSurveyDialog.vue, src/utils/FetchConfig.ts, tests/unit/FilingSurveyDialog.spec.ts
- added js-cookie package
- added hotjar-shared config for IA_SURVEY_ID
- fetch IA_SURVEY_ID
- added code to launch filing survey
- added code to set/get/remove cookie
- app version = 4.5.8
=> 14429 Filing Survey dialog and launch filing survey

package-lock.json, package.json, src/App.vue, src/utils/FetchConfig.ts
- misc filing survey fixes (see PR comments for details)
- app version = 4.5.9
=> 14429 Misc filing survey fixes

package-lock.json, package.json, src/dialogs/FilingSurveyDialog.vue, tests/unit/FilingSurveyDialog.spec.ts
- updated close button color
- updated action button labels
- app version = 4.5.10
=> 14429 Misc filing survey UI/UX updates

package-lock.json, package.json, src/components/common/RegAddEditOrgPerson.vue, src/dialogs/FilingSurveyDialog.vue, src/enums/restorationTypes.ts, src/interfaces/stepper-interfaces/AddPeopleAndRole/people-and-roles-resource-interface.ts, src/mixins/add-edit-org-person-mixin.ts, src/resources/Restoration/BC.ts, src/resources/Restoration/BEN.ts, src/resources/Restoration/CC.ts, src/resources/Restoration/ULC.ts, src/store/getters/resource-getters.ts, tests/unit/FilingSurveyDialog.spec.ts
*Issue #:* bcgov/entity#14798 and bcgov/entity#14429
Commit 1:
- removed roles title/subtitle (template, interface, resources)
- removed obsolete roles (relationships)
- updated restoration types enum
- updated roles logic
- app version = 4.5.11
Commit 2:
- updated filing survey title
- updated filing survey blurb
=> 14798 More incremental resto work + 14429 Updated filing survey text

package-lock.json, package.json, src/App.vue, src/utils/FetchConfig.ts
_Sorry about all these changes. The business keeps "refining" their requirements. 😳_
- change from cookie (which expires) to local storage (which doesn't)
- uninstall js-cookie package
- app version = 4.5.12
=> 14429 Change "hide survey" from cookie to local storage

package-lock.json, package.json, src/App.vue, src/components/common/ListPeopleAndRoles.vue, src/components/common/RegPeopleAndRoles.vue, src/components/common/RuleListItem.vue, src/components/common/Stepper.vue, src/enums/roleTypes.ts, src/interfaces/filing-interfaces/filing-interfaces.ts, src/interfaces/resource-interfaces/resource-interface.ts, src/interfaces/stepper-interfaces/AddPeopleAndRole/people-and-roles-resource-interface.ts, src/interfaces/store-interfaces/state-interfaces/restoration-state-interface.ts, src/mixins/add-edit-org-person-mixin.ts, src/mixins/filing-template-mixin.ts, src/mixins/people-roles-mixin.ts, src/store/getters/state-getters.ts, src/store/state/state-model.ts, src/views/Registration/RegistrationReviewConfirm.vue, src/views/Restoration/RestorationReviewConfirm.vue, tests/unit/App.spec.ts, tests/unit/ListPeopleAndRoles.spec.ts, tests/unit/RegPeopleAndRoles.spec.ts, tests/unit/RuleListItem.spec.ts
*Issue #:* bcgov/entity#14798
Commit 1:
- don't render fee summary until data is loaded
- don't check FF if Jest is running
- added conditional columns to ListPeopleAndRoles
- added Email column to ListPeopleAndRoles
- disable add buttons when there is a valid applicant
- auto-assign Applicant role
- deleted obsolete roles
- used shared Contact Point interface
- added restoration properties to interface
- used sub-component for rule list items
- create RuleListItem component
- fixed applicant information validation
- misc cleanup (including some TODO comments)
- created/updated unit tests
- app version = 4.5.13
Commit 2:
- reordered v-cards
- updated labels
- updated Document Delivery props
- updated DocumentDelivery dependency
By submitting this pull request, I …
=> 14798 Remaining implementation of Applicant Information

package-lock.json, package.json, src/components/common/ListPeopleAndRoles.vue, src/interfaces/filing-interfaces/filing-interfaces.ts, src/mixins/filing-template-mixin.ts, tests/unit/BusinessName.spec.ts, tests/unit/SummaryRestoreBusiness.spec.ts
*Issue #:* bcgov/entity#14783
- added missing nameRequest property
- updated Restoration Filing interface to match schema
- conditionally saved Court Order object
- updated List People And Roles column alignment
- implemented Summary Restore Business test suite
- app version = 4.6.3
=> 14783 Misc fixes + unit tests

package-lock.json, package.json, src/components/Restoration/RestorationType.vue, src/mixins/filing-template-mixin.ts, src/views/Restoration/RestorationBusinessName.vue
*Issue #:* /bcgov/entity#14797
- Final update to the restoration type design.
- New Default State:
- New error state of relationships:
- An overall view:
@ethantspitt Please take a look and waiting for your feedback.
=> Fix restoration type ux

package-lock.json, package.json, src/App.vue
*Issue #:* /bcgov/entity#15183
- The names of the feature flags changed in LaunchDarkly.
=> 15183 Fixed webchat feature flags name to stay consistent with LD

package-lock.json, package.json, src/components/common/RegAddEditOrgPerson.vue
*Issue #:* /bcgov/entity#15173
=> Create UI: text update for restoration edit business or corporation

package-lock.json, package.json, src/components/common/RegistriesContactInfo.vue, tests/unit/RegistriesContactInfo.spec.ts
*Issue #:* /bcgov/entity#15543
Update IT OPS contact number to HELP DESK contact number
=> Update contact phone number

package-lock.json, package.json, src/mixins/filing-template-mixin.ts
*Issue #:* bcgov/entity#15832
- app version = 5.0.3
- updated browserslist
- don't save applicationDate if it's empty
- don't save noticeDate if it's empty
=> 15832 Fixed null JSON properties

package-lock.json, package.json
*Issue #:* /bcgov/entity#15969
=> 15969 upgrade ApprovalType component

package-lock.json, package.json, src/App.vue, src/mixins/filing-template-mixin.ts
*Issue #:* bcgov/entity#16175
- app version = 5.2.2
- fixed fee summary style issue
- removed restoration original legal name
=> 16175 Small fixes

package-lock.json, package.json, src/views/Incorporation/IncorporationReviewConfirm.vue, tests/unit/IncorporationReviewConfirm.spec.ts
*Issue :* /bcgov/entity#13995
- Show Staff Payment section when IA as staff
- Add unit test
**Before**
**After**
=> 13995 Show Staff Payment section when IA as staff

package-lock.json, package.json, src/interfaces/filing-interfaces/filing-interfaces.ts, src/mixins/filing-template-mixin.ts, src/store/store.ts
*Issue #:* /bcgov/entity#13995
- Fix bugs for staff payment section of IA
In IA, staff payment should not go through when providing incorrect information.
=> 13995 Fix bugs - Show Staff Payment section when IA as staff

package-lock.json, package.json, src/components/Registration/StartDate.vue, src/rules/date-rules.ts, src/views/Registration/RegistrationDefineBusiness.vue, tests/unit/RegistrationStartDate.spec.ts
*Issue #:* bcgov/entity#16548
- app version = 5.2.7
- changed min date to 10 years ago
- removed min start date for staff
- removed min validation for staff
- added some date rules
- updated start date message for staff
- updated start date message for reg users (10 vs 2 years in the past)
- updated a unit test
=> 16548 Update SP/GP start date validation

package-lock.json, package.json, src/App.vue, src/components/Dissolution/CompleteAffidavit.vue, src/components/Incorporation/UploadMemorandum.vue, src/components/Incorporation/UploadRules.vue, src/dialogs/PaymentErrorDialog.vue, src/dialogs/SaveErrorDialog.vue, src/interfaces/store-interfaces/state-interfaces/tombstone-interface.ts, src/store/state/state-model.ts, src/store/store.ts, tests/unit/Actions.spec.ts, tests/unit/AddEditOrgPerson.spec.ts, tests/unit/App.spec.ts, tests/unit/DissolutionFirm.spec.ts, tests/unit/DissolutionReviewConfirm.spec.ts, tests/unit/FetchErrorDialog.spec.ts, tests/unit/IncorporationReviewConfirm.spec.ts, tests/unit/PaymentErrorDialog.spec.ts, tests/unit/RegistrationReviewConfirm.spec.ts, tests/unit/RestorationApplicantInformation.spec.ts, tests/unit/RestorationBusinessInformation.spec.ts, tests/unit/RestorationBusinessName.spec.ts, tests/unit/RestorationReviewConfirm.spec.ts, tests/unit/SaveErrorDialog.spec.ts
*Issue #:* bcgov/entity#16444
- app version = 5.2.7
- cleaned up a couple of dialogs
- renamed some state variables and getters/setters
- get user's roles from Keycloak token
- used proper roles in LaunchDarkly update
- misc cleanup
=> 16444 Use Keycloak roles for LaunchDarkly update

package-lock.json, package.json, src/components/Registration/StartDate.vue, tests/unit/RegistrationStartDate.spec.ts
*Issue #:* bcgov/entity#15018
- app version = 5.2.8
- fixed startDateMax
=> 15018 Fix max business start date

package-lock.json, package.json, src/App.vue, src/dialogs/AccountContactMissingDialog.vue, src/dialogs/index.ts, src/enums/errorTypes.ts, src/enums/index.ts, tests/unit/AccountContactMissingDialog.spec.ts
*Issue #:*[ /bcgov/entity14946](https://github.com/bcgov/entity/issues/14946)
=> 14946 - Add  a new dialog for account missing email and phone

package-lock.json, package.json, src/components/Dissolution/CompleteResolution.vue
*Issue #:* bcgov/entity#17765
This is a fix for ops-support ticket # 3105.
- app version = 5.4.3
- another fix to previewImageSource()
=> ops-support-3105 More fixes

.github/workflows/cd.yml, .github/workflows/ci.yml, Dockerfile, devops/cloudbuild-pr.yaml, package-lock.json, package.json
*Issue #:* bcgov/entity#17594
- app version = 5.5.0
- updated Dockerfile
- updated CD script
- updated CI script
- updated PR script
=> 17594 Updates for Node 20

package-lock.json, package.json, src/App.vue, src/components/common/RegAddEditOrgPerson.vue, src/rules/first-name-rules.ts, src/rules/index.ts, tests/unit/RegAddEditOrgPerson.spec.ts
*Issue #:* /bcgov/entity#17795
- Removed invalid first name error
- Changed first name rule of completing party for registration
- Changed `certifiedBy` value
- app version = 5.5.2
=> 17795 Allow registration (SP/GP) for an user/account that only uses last name

package-lock.json, package.json, src/components/Restoration/RestorationType.vue, src/views/Restoration/RestorationBusinessName.vue
*Issue #:* /bcgov/entity#15863
- Fixed the red overflow of the invalid visible state. 
=> 15863 fixed the red invalid state sizing issue and some reshaping

package-lock.json, package.json, src/components/Amalgamation/AmalgamatingBusinesses.vue, src/components/Amalgamation/BusinessStatus.vue, src/components/common/Stepper.vue, src/enums/amalgamationEnums.ts, src/mixins/amalgamation-mixin.ts, src/store/store.ts, src/views/AmalgamationRegular/Information.vue, src/views/AmalgamationRegular/ReviewConfirm.vue
*Issue #:* bcgov/entity#18971
- app version = 5.6.12
- finished stepper validity code
- cleaned up some store code
- misc cleanup
- named and sorted rules - **to be continued when requirements are cleaned up**
- added spinner (experimental) - **tell me what you think about this**
=> 18971 Finished some TODOs and incremental work on amalgamating business validations

package-lock.json, package.json, src/components/Amalgamation/AmalgamatingBusinesses.vue, src/mixins/amalgamation-mixin.ts
*Issue #:* /bcgov/entity#19019
- Add extra-pro TING companies to the table (treating them as foreign)
- Refactored code
- Fixed the rules
=> 19019 Add extra-pro A TING companies

package-lock.json, package.json, src/assets/styles/base.scss, src/views/AmalgamationRegular/ReviewConfirm.vue
*Issue #:* bcgov/entity#19109
- app version = 5.6.22
- updated base class to remove border radius (per UI designs)
- added message box to step 5
Sample:
=> 19109 Added caution to review step

package-lock.json, package.json, src/views/AmalgamationRegular/ReviewConfirm.vue
*Issue #:* bcgov/entity#19109
- app version = 5.6.23
- fixed amalgamation information title
Screenshot:
=> 19109 Fixed section title

package-lock.json, package.json, src/components/common/NameRequestInfo.vue
*Issue #:* bcgov/entity#19136
- app version = 5.6.24
- reordered sections so amalgamations don't use generic section
=> 19136 Fixed resulting business name display

tests/unit/NameRequestInfo.spec.ts
*Issue #:* /bcgov/entity#18641
=> 18641 Implement new Amalgamating Businesses component - Part IV

package-lock.json, package.json, src/services/legal-services.ts
=> add account id header

package-lock.json, package.json, src/mixins/filing-template-mixin.ts
*Issue #:* bcgov/entity#19210
- app version = 5.6.33
- do not save numbered name
- do not restore numbered name
=> 19210 Do not save or restore the numbered name

package-lock.json, package.json, src/components/Amalgamation/AmalgamatingBusinesses.vue, src/enums/filingStatus.ts
*Issue #:* bcgov/entity#19050
- app version = 5.6.34
- fixed check for future effective filing
- added missing filing statuses to enum
=> 19050 Fixed future effective check

package-lock.json, package.json, src/resources/AmalgamationRegular/BC.ts, src/resources/AmalgamationRegular/BEN.ts, src/resources/AmalgamationRegular/CC.ts, src/resources/AmalgamationRegular/ULC.ts
*Issue #:* bcgov/entity#19274
- app version = 5.6.39
- disabled incorporator/organization code for amalgamations
=> 19274 Removed organizations (and incorporator) from amalgamations

package-lock.json, package.json, src/components/Amalgamation/AmalgamatingBusinesses.vue, tests/unit/Actions.spec.ts, tests/unit/AddEditOrgPerson.spec.ts, tests/unit/AmalgamatingBusinesses.spec.ts, tests/unit/App.spec.ts, tests/unit/BusinessName.spec.ts, tests/unit/FileUploadPreview.spec.ts, tests/unit/RegAddEditOrgPerson.spec.ts, tests/unit/RegPeopleAndRoles.spec.ts, tests/unit/RestorationType.spec.ts, tests/unit/SummaryRestoreBusiness.spec.ts
*Issue #:* bcgov/entity#19179
**This is only a subset of unit tests, but I think we can merge them in now and I'll create another PR for the others.**
- app version = 5.6.40
- added element ids
- updated LEAR business duplicate check
- added foreign business duplicate check
- misc cleanup
- added test suite (WIP)
=> 19179 Added Amalgamating Businesses unit tests

package-lock.json, package.json, tests/unit/AmalgamatingBusinesses.spec.ts
*Issue #:* bcgov/entity#19179
- app version = 5.6.41
- added rest of unit tests
=> 19179 Added rest of amalgamating businesses unit tests

package-lock.json, package.json, src/components/Amalgamation/BusinessTable.vue, tests/unit/BusinessTable.spec.ts
*Issue #:* /bcgov/entity#19359
Increased businesses table check from > 0 to > 1
=> 19359 - Amalgamating Businesses Table must have more than 1

package-lock.json, package.json, src/components/common/PeopleAndRoles.vue, src/interfaces/resource-interfaces/resource-interface.ts, src/interfaces/stepper-interfaces/AddPeopleAndRole/people-and-roles-resource-interface.ts, src/resources/AmalgamationRegular/BC.ts, src/resources/AmalgamationRegular/BEN.ts, src/resources/AmalgamationRegular/CC.ts, src/resources/AmalgamationRegular/ULC.ts, src/resources/AmalgamationShort/BC.ts, src/resources/AmalgamationShort/BEN.ts, src/resources/AmalgamationShort/CC.ts, src/resources/AmalgamationShort/ULC.ts, src/store/store.ts, src/views/Amalgamation/BusinessInfo.vue
*Issue #:* bcgov/entity#19040
- app version = 5.7.1
- don't show Add Person for short-form amalgamation
- set initial OfficeAddresses validity
- deleted unneeded data from amalg IF
- finished short amalg Office Addresses layout
=> 19040 Misc short-form amalg framework fixes

package-lock.json, package.json, src/components/Amalgamation/AmalgamatingBusinesses.vue, src/components/Amalgamation/BusinessTable.vue, src/components/Amalgamation/BusinessTableSummary.vue, src/enums/amalgamationEnums.ts, src/views/Amalgamation/BusinessInfo.vue, src/views/Amalgamation/Information.vue, src/views/Amalgamation/ReviewConfirm.vue, tests/unit/AmalgamatingBusinesses.spec.ts, tests/unit/BusinessTable.spec.ts, tests/unit/BusinessTableSummary.spec.ts
*Issue #:* bcgov/entity#19036
- app version = 5.8.2
- added handling for PRIMARY vs HOLDING
- changed some "xxx Company" to "xxx Business" per uxpin changes
- added separate information blurb for horizontal amalg
- removed message box from review page (all amalgs) per uxpin changes
- added/updated unit tests
*Example:*
=> 19036 Added handling for Primary vs Holding + misc UI updates

package-lock.json, package.json, src/components/Amalgamation/ResultingBusinessName.vue, src/mixins/filing-template-mixin.ts, src/views/Amalgamation/Information.vue
*Issue #:* /bcgov/entity#19039
Show the name and business type of the holding company
=> 19039-show-resulting-name-and-business-type

package-lock.json, package.json, src/components/common/ListPeopleAndRoles.vue, src/components/common/PeopleAndRoles.vue, src/interfaces/stepper-interfaces/AddPeopleAndRole/people-and-roles-resource-interface.ts, src/resources/AmalgamationShort/BC.ts, src/resources/AmalgamationShort/BEN.ts, src/resources/AmalgamationShort/CC.ts, src/resources/AmalgamationShort/ULC.ts, tests/unit/ListPeopleAndRoles.spec.ts
*Issue #:* /bcgov/entity#19458
- do not display directors on Add People and Roles page
- show directors on Review and Confirm page
- add unit tests
People and Roles step:
Review and Confirm step:
Tested people and Roles step for other filing types and seem to be working as before.
=> 19458 - do not show/edit directors

.env.example
*Issue #:* /bcgov/entity#19193
updated to use new gcp url
=> 19193 updated env legal name

package-lock.json, package.json, src/mixins/amalgamation-mixin.ts, src/mixins/filing-template-mixin.ts, src/services/legal-services.ts
*Issue #:* bcgov/entity#20196
- app version = 5.9.9
- cleaned up some code
- added fallback (to empty string) for business email to all  filings
- added fallback (to empty string) for business phone to all filings
- don't initialize isBusinessLookup when fetching directors (ie, leave it undefined)
=> 20196 Added some fallbacks to prevent invalid JSON

package-lock.json, package.json, src/mixins/filing-template-mixin.ts, tests/unit/Actions.spec.ts, tests/unit/filing-template-mixin.spec.ts
*Issue #:* bcgov/entity#20489
- app version = 5.9.11
- saved correct name option for other filings (not used but denotes code intent for future debugging/audit)
=> 20489 Misc cleanup

package-lock.json, package.json, src/interfaces/filing-interfaces/filing-interfaces.ts, src/mixins/filing-template-mixin.ts
*Issue #:* bcgov/entity#20931
- app version = 5.9.12
- now save business object in registration filing
=> 20931 Now save business object in registration filing

package-lock.json, package.json, src/App.vue, src/components/Dissolution/AssociationDetails.vue, src/components/Dissolution/CompleteAffidavit.vue, src/components/common/EntityInfo.vue, src/interfaces/store-interfaces/state-interface.ts, src/interfaces/store-interfaces/state-interfaces/business-interface.ts, src/mixins/document-mixin.ts, src/store/state/state-model.ts, src/store/store.ts, src/utils/Navigate.ts, src/utils/feature-flag-utils.ts, src/views/Dissolution/DissolutionDefineDissolution.vue, src/views/DissolutionFirm/DissolutionFirm.vue, tests/unit/App.spec.ts, tests/unit/AssociationDetails.spec.ts, tests/unit/EntityInfo.spec.ts
*Issue #:* /bcgov/entity#20779
Implemented the easy legal name fix 
=> 20779 Implemented Easy Legal Name Fix

package-lock.json, package.json
*Issue #:* /bcgov/entity#20946
updated to use latest alternate name interface
=> 20946 updated to use latest alternate name interface

package-lock.json, package.json, src/assets/styles/base.scss, src/assets/styles/theme.scss, src/components/Amalgamation/AmalgamatingBusinesses.vue, src/components/Dissolution/CompleteResolutionSummary.vue, src/components/common/AddEditOrgPerson.vue, src/components/common/MessageBox.vue, src/components/common/RegAddEditOrgPerson.vue, src/views/Amalgamation/BusinessInfo.vue, src/views/ContinuationIn/ContinuationInReviewConfirm.vue, src/views/Dissolution/DissolutionDefineDissolution.vue, src/views/DissolutionFirm/DissolutionFirm.vue, tests/unit/AmalgamationBusinessInfo.spec.ts
*Issue #:* bcgov/entity#19264
- app version = 5.10.2
- removed base SCSS and moved it into new component
- added a theme colour
- replaced v-cards with message-box class with new MessageBox component
- added new MessageBox component
- misc aleanup
=> 19264 Added MessageBox common component

package-lock.json, package.json, src/components/ContinuationIn/ContinuationAuthorization.vue, src/components/ContinuationIn/ExtraproRegistration.vue, src/components/ContinuationIn/SummaryBusinessHomeJurisdiction.vue, src/components/Dissolution/CompleteAffidavit.vue, src/components/Incorporation/UploadMemorandum.vue, src/components/Incorporation/UploadRules.vue, src/components/common/FileUploadPreview.vue, src/interfaces/filing-interfaces/continuation-authorization-interface.ts, src/interfaces/filing-interfaces/existing-business-info-interface.ts, src/interfaces/filing-interfaces/filing-interfaces.ts, src/interfaces/index.ts, src/interfaces/store-interfaces/state-interfaces/continuation-in-state-interface.ts, src/interfaces/utils-interfaces/document-upload-interface.ts, src/interfaces/utils-interfaces/presigned-url-interface.ts, src/mixins/document-mixin.ts, src/mixins/filing-template-mixin.ts, src/store/state/state-model.ts, src/store/store.ts, src/utils/AxiosInstance.ts, src/views/ContinuationIn/ContinuationInBusinessHome.vue, tests/unit/FileUploadPreview.spec.ts
*Issue #:* bcgov/entity#19265
- app version = 5.10.5
- added hint prop to file upload component
- misc renaming in file upload component
- misc cleanup in file upload component (not a refactor)
- added Continuation Authorization component
- updated continuation authorization code in summary component
- very minor cleanup of Complete Affidait component (re: file upload)
- very minor cleanup of Upload Memorandum component
- very minor cleanup of Upload Rules component
- added Continuation Authorization interface
- added misc comments
- updated filing build/parse code
- updated Cont In first step
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of the bcrs-entities-create-ui license …
=> 19265 added Continuation Authorization component

package-lock.json, package.json, src/components/ContinuationIn/ContinuationAuthorization.vue, src/components/ContinuationIn/SummaryBusinessHomeJurisdiction.vue, src/components/Dissolution/CompleteAffidavit.vue, src/components/Incorporation/UploadMemorandum.vue, src/components/Incorporation/UploadRules.vue, src/components/common/FileUploadPreview.vue, src/mixins/document-mixin.ts, src/services/legal-services.ts, tests/unit/FileUploadPreview.spec.ts
*Issue #:* bcgov/entity#19265
- app version = 5.10.6
- updated file upload custom error handling to sync with parent if needed
- simplified file upload validation flow
- added handling for failure to retrieve file info (invalid PDF)
- updated a blurb per Yui
- show "File uploaded" instead of default hint for loaded files
- show custom errors on specific upload instance only
- updated date rules/validation
- updated fallback message if null expiry date
- misc cleanup and comments
- combined/updated unit tests
=> 19265 Updated file upload validation, etc

package-lock.json, package.json, src/components/ContinuationIn/ContinuationAuthorization.vue, src/components/ContinuationIn/ExtraproBusinessLookup.vue, src/components/common/FileUploadPreview.vue, src/views/ContinuationIn/ContinuationInReviewConfirm.vue, src/views/ContinuationIn/ContinuationInShareStructure.vue, tests/unit/ContinuationAuthorization.spec.ts, tests/unit/ContinuationInBusinessBc.spec.ts, tests/unit/ContinuationInBusinessHome.spec.ts, tests/unit/ContinuationInPeopleRoles.spec.ts, tests/unit/ContinuationInReviewConfirm.spec.ts, tests/unit/ContinuationInShareStructure.spec.ts, tests/unit/ExtraproBusinessLookup.spec.ts, tests/unit/ExtraproRegistration.spec.ts
*Issue #:* bcgov/entity#21235
- app version = 5.10.7
- misc cleanup
- removed continuation authorization snackbar
- added test suites for new Cont In views and components
=> 21235 Added unit tests + misc cleanup

package-lock.json, package.json, src/components/ContinuationIn/ContinuationAuthorization.vue, src/components/ContinuationIn/ExtraproRegistration.vue, src/components/ContinuationIn/SummaryBusinessHomeJurisdiction.vue, src/components/common/SummaryDefineCompany.vue, src/interfaces/filing-interfaces/continuation-authorization-interface.ts, src/interfaces/filing-interfaces/existing-business-info-interface.ts, src/mixins/filing-template-mixin.ts, src/resources/ContinuationIn/steps.ts, src/views/ContinuationIn/ContinuationInReviewConfirm.vue, tests/unit/ContinuationAuthorization.spec.ts, tests/unit/SummaryBusinessHomeJurisdiction.spec.ts
*Issue #:* bcgov/entity#21138 (partial implementation)
- app version = 5.10.9
- updated Continuation Authorization layout
- removed continuation authorization authority name
- added continuation authorization date hints
- removed continuation authorization confirmation checkbox
- updated continuation authorization header blurb
- updated review page
- updated interface
- updated filing resume code (parse)
- updated/added unit tests
- misc cleanup
=> 21138 Updated layouts per recent design changes, etc

package-lock.json, package.json, src/store/store.ts, src/views/Incorporation/IncorporationReviewConfirm.vue
*Issue #:* /bcgov/entity#Fix 21241
- Fixed the issue in Review and Confirmation Page
=> Fix 21241 - Hide-Court-Order - Fixed-Review-Confirmation

package-lock.json, package.json, src/components/ContinuationIn/ContinuationAuthorization.vue, src/components/ContinuationIn/ExtraproRegistration.vue, src/components/ContinuationIn/ManualBusinessInfo.vue, src/components/ContinuationIn/SummaryBusinessHomeJurisdiction.vue, src/components/common/FileUploadPreview.vue, tests/unit/FileUploadPreview.spec.ts
*Issue #:* bcgov/entity#21248 (partial implementation)
- app version = 5.10.14
- added validation for PDF file extension
- moved FileUploadPreview class to top level
- updated FileUploadPreview styles and unit tests
- added incorporation date rules
- added Registration in Home Jurisdiction editable field
- misc cleanup
=> 21248 File extension validation + extra date validation + editable Registration in Home Jurisdiction field

package-lock.json, package.json, src/components/ContinuationIn/ExtraproRegistration.vue, src/components/ContinuationIn/ManualBusinessInfo.vue, src/components/ContinuationIn/UploadAffidavit.vue, tests/unit/ContinuationInUploadAffidavit.spec.ts, tests/unit/ManualBusinessInfo.spec.ts
*Issue #:* /bcgov/entity#21315
- Added Upload Director's Affidavit component for manual input
- Restructured code, added a new sub-component UploadAffidavit
=> 21315 - Upload Director's Affidavit

package-lock.json, package.json, src/components/ContinuationIn/ManualBusinessInfo.vue, src/components/ContinuationIn/UploadAffidavit.vue, tests/unit/ExtraproRegistration.spec.ts, tests/unit/ManualBusinessInfo.spec.ts
*Issue #:* bcgov/entity#21452
- app version = 5.10.18
- updated Jurisdiction component initial value
- deleted unneeded getter
- cleaned up test suite
=> 21452 Updated Jurisdiction component initial value

package-lock.json, package.json, src/components/ContinuationIn/ExtraproRegistration.vue, src/components/ContinuationIn/ManualBusinessInfo.vue, src/store/store.ts
*Issue #:* bcgov/entity#21450
**The changes in this PR are not related to the subject ticket (which doesn't reproduce). This is a bit of cleanup that I did after ongoing testing of a Continuation In filing.**
- app version = 5.10.19
- set HaveChanges when user has made changes
=> 21450 Set HaveChanges when user has made changes

package-lock.json, package.json, src/components/Amalgamation/AmalgamatingBusinesses.vue, src/services/business-lookup-services.ts, src/utils/FetchConfig.ts
*Issue #:* bcgov/entity#21134
- app version = 5.10.21
- imported latest Business Lookup shared component
- added C, CBEN, CCC and CUL to amalgamation business search
- renamed getters and session storage key to better match environment key names
=> 21134 Added continued in entity types to business searches

package-lock.json, package.json, src/mixins/filing-template-mixin.ts
*Issue #:* bcgov/entity#21638
- app version = 5.10.22
- don't save expiry date if it's null
=> 21638 Don't save expiry date if it's null

package-lock.json, package.json, src/interfaces/filing-interfaces/filing-interfaces.ts, src/mixins/filing-template-mixin.ts
*Issue #:* bcgov/entity#21638
- app version = 5.10.23
- don't save authorization object if it's null/undefined
=> 21638 Don't save authorization object if it's null/undefined

package-lock.json, package.json, src/components/common/EntityInfo.vue, tests/unit/EntityInfo.spec.ts
*Issue #:* bcgov/entity#21116
- app version = 5.10.24
- show user info for Continuation In filings
=> 21116 Show user info for Continuation In filings

src/components/ContinuationIn/SummaryBusinessHomeJurisdiction.vue, tests/unit/SummaryBusinessHomeJurisdiction.spec.ts
*Issue #:* bcgov/entity#21110
- updated labels on review page
=> 21110 Updated labels on review page

package-lock.json, package.json, src/components/ContinuationIn/ContinuationAuthorization.vue, src/components/ContinuationIn/ExtraproRegistration.vue, src/components/ContinuationIn/ManualBusinessInfo.vue
*Issue #:* /bcgov/entity#21599
- Step one will only show the Tick Mark and errors, after the user visits the Review and Confirm Page
- The authorization date picker will reset, if the incorporation date is changes to a date after the current selected authorization date. (Otherwise the component will be valid regardless of the invalid authorization date)
=> 21599 - Updated Step One Tick Mark Issue

package-lock.json, package.json, src/components/ContinuationIn/ContinuationAuthorization.vue
*Issue #:* /bcgov/entity#21599
- Added validity check for Expiry Date
=> Fix 21599 - Step One Tick Mark - Expiry Date Error

package-lock.json, package.json, src/components/ContinuationIn/ContinuationAuthorization.vue, src/components/ContinuationIn/SummaryBusinessHomeJurisdiction.vue, src/interfaces/store-interfaces/state-interfaces/continuation-authorization-interface.ts, src/mixins/filing-template-mixin.ts, tests/unit/ContinuationAuthorization.spec.ts, tests/unit/SummaryBusinessHomeJurisdiction.spec.ts
*Issue #:* bcgov/entity#21895
- app version = 5.11.1
- removed Expiry Date from Continuation Authorization component
- removed Expiry Date from Summary component
- vertically aligned file buttons with label on Summary page
- removed Expiry Date from interface
- removed Expiry Date from filing resume draft
=> 21895 Removed Authorization Expiry

package-lock.json, package.json, src/App.vue
*Issue #:* /bcgov/entity#19483
- Ticket #19483
- Updated App.vue to enable Staff Payment data saved and restored
- Completed validation, checked unit tests have been added for new components and pages
=> 19483 - Staff Payment Restore

package-lock.json, package.json, src/views/Amalgamation/BusinessInfo.vue, src/views/ContinuationIn/ContinuationInBusinessBc.vue, src/views/Incorporation/IncorporationDefineCompany.vue, src/views/Restoration/RestorationBusinessInformation.vue, tests/unit/AmalgamationBusinessInfo.spec.ts
*Issue #:* /bcgov/entity#19483
- Updated the sentence in Registered Office Address for Amal/Incorp/ContIn/Resto
- Fix Ticket #19483
=> Fixed-19483-Spelling and Grammar in Address Component

.github/workflows/ci.yml
*Issue #:* /bcgov/entity#22248
Same as https://github.com/bcgov/business-filings-ui/pull/678
=> 22248 - Disable codecov failure

package-lock.json, package.json, src/App.vue, src/components/ContinuationIn/ContinuationAuthorization.vue, src/components/common/EffectiveDateTime.vue, src/views/ContinuationIn/ContinuationInBusinessHome.vue, src/views/ContinuationIn/ContinuationInReviewConfirm.vue, tests/unit/ContinuationAuthorization.spec.ts, tests/unit/ContinuationInBusinessHome.spec.ts
*Issue #:* bcgov/entity#22549
- app version = 5.11.10
- enable validation right away if filing is Change Requested
- added label props to effective data time component
- updated continuation authorization layout per designs
- now manage authorization files validity separately
- passed in custom values for radio button labels
=> 22549 Misc updates for change-requested continuation application

package-lock.json, package.json, src/components/ContinuationIn/ContinuationAuthorization.vue
*Issue #:* bcgov/entity#22549
- app version = 5.11.11
- adjust message box icon size, font size, and whitespace
=> 22549 Small message box UI tweaks

package-lock.json, package.json, src/App.vue
*Issue #:* bcgov/entity#22644
- app version = 5.11.12
- conditionally show fee summary
=> 22644 Hide fee summary for change-requested filings

package-lock.json, package.json, src/resources/Dissolution/BC.ts, src/resources/Dissolution/BEN.ts, src/resources/Dissolution/C.ts, src/resources/Dissolution/CBEN.ts, src/resources/Dissolution/CC.ts, src/resources/Dissolution/CCC.ts, src/resources/Dissolution/CP.ts, src/resources/Dissolution/CUL.ts, src/resources/Dissolution/ULC.ts
*Issue #:* /bcgov/entity#22781
- This was the bug that was talked about in the meeting. Took me a second to fix and it seems it was important for Dylan to be fixed.
=> 22781 - Fixed dissolution wording

package-lock.json, package.json, src/App.vue
*Issue #:* /bcgov/entity#22938
- Update the setBusinessId method to support Continuation type businesses.
=> 22938 - Fix the bug when dissolute a ContIn

package-lock.json, package.json, src/store/store.ts, src/views/Incorporation/IncorporationReviewConfirm.vue
*Issue #:* /bcgov/entity#22146
- Fixed the bug that: Unable to file a CO-OP fling when logged in as a staff user
By fixing the Review and Confirm page bug. (Court Order section validity)
=> 22146 - Fixed the CO-OP Incorporation Review Page Bug

package-lock.json, package.json, src/components/Restoration/RestorationType.vue
*Issue #:* bcgov/entity#15538
- app version = 5.11.19
- imported latest Relationships Panel shared component
- adjusted whitespace
- passed in validation prop
=> 15538 Fixed validation for relationship types

package-lock.json, package.json, src/components/Restoration/ApprovalType.vue
*Issue #:* /bcgov/entity#15538
- Fixed the bug that restoration Approval Type is not updated
=> Fix 15538 - Restoration Approval Type Bug

package-lock.json, package.json, src/assets/styles/base.scss, src/components/ContinuationIn/ContinuationAuthorization.vue, src/components/ContinuationIn/ManualBusinessInfo.vue, src/components/common/FileUploadPreview.vue, tests/unit/ContinuationAuthorization.spec.ts
*Issue #:* bcgov/entity#22995
- app version = 5.11.23
- added helpful base class
- added public "open" method to file uploader
- deleted unneeded v-form
- refactored multi-file upload per new design
- removed page size restriction
=> 22995 Change multi-file upload to new design

package-lock.json, package.json, src/components/ContinuationIn/ContinuationAuthorization.vue, src/components/common/FileUploadPreview.vue
*Issue #:* bcgov/entity#22995
- app version = 5.11.26
- refactored file input rules to emit error messages
- separated onFileSelected and onRemoveClicked to simplify code
=> 22995 Updated file validation

package-lock.json, package.json, src/components/Amalgamation/ResultingBusinessName.vue, src/components/Restoration/BusinessName.vue, src/components/common/NameRequestInfo.vue, src/components/common/NameTranslations.vue, src/views/ContinuationIn/ContinuationInAuthorization.vue, src/views/ContinuationIn/ContinuationInBusinessBc.vue, src/views/Incorporation/IncorporationDefineCompany.vue, src/views/Restoration/RestorationBusinessName.vue, tests/unit/ContinuationInAuthorization.spec.ts, tests/unit/ContinuationInBusinessBc.spec.ts
*Issue #:* bcgov/entity#23822
- app version = 5.12.7
- added divider and updated whitespace for amalgamation
- removed base padding for name translation component
- updated header, added divider, updated whitespace and updated validation for continuation authorization
- updated header, added divider and updated whitespace for continuation application
- added divider and updated whitespace for incorporation
- added divider and updated whitespace for restoration
=> 23822 Update NR display for authorization and application

package-lock.json, package.json, src/components/ContinuationIn/ExtraproRegistration.vue, src/components/ContinuationIn/ManualBusinessInfo.vue, src/components/common/ShareStructure.vue, src/views/Amalgamation/ShareStructure.vue, src/views/ContinuationIn/ContinuationInReviewConfirm.vue, src/views/ContinuationIn/ContinuationInShareStructure.vue, src/views/Incorporation/IncorporationShareStructure.vue, tests/unit/ContinuationInReviewConfirm.spec.ts, tests/unit/ContinuationInShareStructure.spec.ts
*Issue #:* bcgov/entity#23833
- app version = 5.12.8
- fixed share structure button styles (outlined)
- added punctuation to some hint text
- bolded and fixed layout of share structure instruction text (x3)
- changed incorporation -> continuation in document delivery section
=> 23833 Small text/style changes

package-lock.json, package.json, src/components/common/ListResolutions.vue
*Issue #:* /bcgov/entity#22846
Updated text as per UX feedback (see below from Jacqueline):
=> 22846 - Update text for resolution or court order dates in Amalgamations

package-lock.json, package.json
*Issue #:* /bcgov/entity#25803
- Update Business-Search Version to use the new CS Type in search list
=> 25803 - Update Business-Search Version (New CS Type)

src/components/ContinuationIn/AuthorizationInformation.vue, src/components/ContinuationIn/SummaryBusinessPreviousJurisdiction.vue, src/enums/documentTypes.ts, src/mixins/document-mixin.ts
*Issue #:* /bcgov/entity#25410
Updated document download component to support DRS and Minio
=> 25410 update download component

package-lock.json, package.json
*Issue #:* /bcgov/entity#25522
=> 25522 update_shared_components

package-lock.json
*Issue #:* /bcgov/entity#25522
=> 25522 fix_missing_version_update

package-lock.json, package.json
*Issue #:* bcgov/entity#26211
- app version = 5.14.10
- changed sbc-common-components to version without SBC Connect changes
=> 26211 changed sbc-common-components to version without SBC Connect changes

package-lock.json, package.json
*Issue #:* bcgov/entity#26351
- app version = 5.14.7a
- imported latest BaseAdress component
=> 26351 imported latest BaseAdress component

package-lock.json, package.json
*Issue #:* /bcgov/entity#26351 
- Update version
- Import latest base-address component
=> 26351 - Import Latest Base-address Component

package-lock.json, package.json
*Issue #:* /bcgov/entity#26394 
- Update app version
- Import latest BaseAddress component
=> 26394 - Import 2.0.42 BaseAddress Component

package-lock.json, package.json, src/mixins/add-edit-org-person-mixin.ts, tests/unit/RegAddEditOrgPerson.spec.ts
*Issue #:* /bcgov/entity#26394 
=> 26394 - Import latest Interface package 

tests/unit/BusinessName.spec.ts
*Issue #:* /bcgov/entity#26104
- Fix the BusinessName unit test
=> Fix 26104 - Correct BusinessName unit test

package-lock.json, package.json
*Issue #:* /bcgov/entity#26560 
- Import BaseAddress (2.0.45)
- Update app version
=> 26560 - Import BaseAddress with Prioritized Countries

index.html, package-lock.json, package.json
*Issue #:* bcgov/entity#26644 
- Change page title
- Update app version
=> 26644 - Update Create-UI Page Title to Create Application

package-lock.json, package.json, src/resources/ContinuationIn/CBEN.ts, src/resources/ContinuationIn/CCC.ts, src/resources/ContinuationIn/CUL.ts
*Issue #:* bcgov/entity/issues/25195
Update to text for CBEN, CCC and CUL
=> 25195 typo in description of continuation in

package-lock.json, package.json, src/resources/Dissolution/steps.ts
*Issue #:* /bcgov/entity#27142
**1. STEP - 1**
**2. STEP - 2**
**3. STEP - 3**
=> 27142 fix inconsistent wording

package-lock.json, package.json, src/mixins/filing-template-mixin.ts
*Issue #:* /bcgov/entity#27221
=> 27221 fix amalg-reg-share-structure restore bug

package-lock.json, package.json, src/components/Amalgamation/AmalgamatingBusinesses.vue
*Issue #:* /bcgov/entity#27609 
- Add check for duplicate entries in table for the unaffiliated business case
https://github.com/user-attachments/assets/0c6e40f1-4420-41e3-b287-975b44763cdb
=> 27609 - Amalgamation Table Allows Duplicate Entry for Unaffiliated Business

package-lock.json, package.json, src/store/store.ts
*Issue #:* /bcgov/entity#28431 
- This issue was only blocking amalgamations for staff 
=> 28431 - Amalgamation is Blocked even though all Components are Showing as Valid

package-lock.json, package.json, src/store/store.ts, src/views/ContinuationIn/ContinuationInBusinessBc.vue
*Issue #:* bcgov/entity#28525 and bcgov/entity#28526
- app version = 5.15.6
- fixed voluntary dissolution validation issue
- fixed continuation in validation issue
=> 28525 + 28526 fixed validation errors

package-lock.json, package.json, src/components/common/TransactionalFolioNumber.vue
*Issue #:* bcgov/entity#28811
- app version = 5.15.8
- fixed Transactional Folio Number initial validity
=> 28811 fixed folio number validation

package-lock.json, package.json, src/resources/BreadcrumbResource.ts, src/services/auth-services.ts, src/services/business-lookup-services.ts, src/services/legal-services.ts, src/store/store.ts, src/utils/AxiosInstance.ts, src/utils/Navigate.ts
*Issue #:* bcgov/entity#28674
- app version = 5.15.11
- renamed getCurrentAccountId -> getAccountId
- replaced store getter with function to get account id in Axios interceptor
=> 28674 small updates for consistency and to prevent future test issues

package-lock.json, package.json, src/components/common/RegAddEditOrgPerson.vue, src/components/common/RegPeopleAndRoles.vue
*Issue #:* /bcgov/entity#29935 
Restoration:
Registration:
=> 29935 - Parameterize the Text in the Applicant Information Section for Email Address

.env.example, devops/vaults.env, package-lock.json, package.json, src/main.ts, src/resources/BreadcrumbResource.ts, src/utils/FetchConfig.ts
*Issue #:* bcgov/entity#30238
- deleted obsolete key VUE_APP_BUSINESSES_URL
- added key VUE_APP_BUSINESS_REGISTRY_URL
- app version = 5.16.10
- fixed MBR breadcrumb URL
- fixed staff dashboard breadcrumb URL
=> 30238 cleaned up some env keys and fixed breadcrumbs

package-lock.json, package.json, src/schemas/address-schemas.ts, tests/unit/OfficeAddresses.spec.ts
*Issue #:* bcgov/entity#30393
- app version = 5.16.14
- imported latest shared BaseAddress
- imported latest shared mixins
- added postal code validation to address schemas
- fixed unit tests
=> 30393 Added postal code validation
